moby/vpnkit

- src/hostnet/lib/slirp.ml
Proxy NTP requests to the NTP listener on localhost.  This allows the
guest to make NTP requests to its default gateway and get a reasonable
answer, as long as the host is answering ntp queries on localhost.
> Send UDP/123 requests to the local IP to localhost.

- src/hostnet/lib/forward.ml
> Throw out excess items when parsing forward socket.

- src/ofs/opam
- src/osx-daemon/opam
- src/osx-hyperkit/opam
- src/proto-vmnet/bin/main.ml
- src/proto-vmnet/opam
> Direct users to the correct URL for source code and bugs.

- src/hostnet/lib/tcpip_stack.ml
> Provide option-6, not option-5, for DNS servers.

- src/hostnet/lib_test/forwarding.ml
- src/hostnet/lib_test/main.ml
- check that we can connect, send and receive data forwarded to a local service
- measure the time taken to perform 10 sequential connections
In particular the timing test will only fail of the connection is outrageously slow: on my MBP 10 connections takes about 0.003s. It will only take more than 1s if there's a > 100ms delay on the average connection.
> Add port forwarding unit tests

- src/hostnet/lib/forward.ml
- src/hostnet/lib/host_uwt.ml
The first three patches upgrade `uwt` and are the same as #74. The last patch fixes the error messages when port forwards fail in "expected" ways, e.g.
- `EADDRINUSE` should be printed as `Bind for %s:%d failed: port is already allocated` i.e. the port is already in use by something else
- `EADDRNOTAVAIL` should be printed as `listen <tcp|udp> %s:%d: bind: cannot assign requested address` i.e. the IP does not exist on the host
The pretty-printed error messages should now be the same as those printed by regular Docker on Linux.
This should remove errors like the mysterious `errno 526` which comes from the Linux 9P client not understanding the error response received from the 9P server in this repo.
> Fix bind errors

- src/hostnet/lib/tcpip_stack.ml
Now that we're using a short lease we generate a lot of logs: one
line per BOOTREQUEST and BOOTREPLY every half (?) lease interval.
This patch logs the first BOOTREQUEST and first BOOTREPLY as `info`
rather than `debug` since these are genuinely useful things to see
in the logs. Subsequent BOOTREQUEST and BOOTREPLY messages are
suppressed. Other message types are logged as `info`.
> Reduce the amount of DHCP log spam

- README.md
This helps me a lot because I can never remember these URLs.
> README.md: add links to artefacts

- README.md
- docs/DNS.md
> docs: add some design notes for DNS forwarding

- appveyor.yml
This copies some changes from docker/datakit's appveyor.yml
> appveyor: attempt to fix build again

- src/hostnet/slirp.ml
This captures UDP packets whose source or destination port is 123.
> Capture up to 64KiB of NTP traffic for debugging

- src/bin/main.ml
Previously we hard-coded the branch name but it's useful to be able to choose via the command-line.
> Add a command-line argument for the db configuration branch

- src/hostnet/vmnet.ml
If the client sends \0 instead of UUID, generate UUID on behalf of
client.
> Allow client to not send UUID

- README.md
The repos are now moby/{vpnkit,hyperkit}
> README.md: update project from docker/ to moby/

- src/hostnet/sig.ml
- src/hostnet/slirp.ml
> Remove trailing whitespace

- reports/2017-06-04.md
Signed-off-by: Anil Madhavapeddy <anil@docker.com>
> dev reports: draft for week 22, now featuring the HTTP libraries as well

- MAINTAINERS
> remove yomimono from maintainers

- vpnkit.opam
Signed-off-by: Thomas Gazagnaire <thomas@gazagnaire.org>
> pin mirage-conduit to an old version

- src/hostnet/slirp.ml
On some systems the creation of a user-space ICMP socket will fail with EPERM. If this happens, don't block startup; instead log a message explaining that ping won't work and continue.
Fixes #286
> ICMP: don't fail to start if we can't create a socket

- go/cmd/vpnkit-forwarder/many.go
- go/pkg/libproxy/multiplexed.go
- go/pkg/libproxy/tcp_proxy.go
> proxy: move helper methods for muliplexed connections from go/cmd/vpnkit-forwarder to go/pkg/libproxy

- go/cmd/vpnkit-iptables-wrapper/main.go
Signed-off-by: Steven Hiehn <shiehn@pivotal.io>
Signed-off-by: Dave Protasowski <dprotaso@gmail.com>
> Fix bug in vpnkit-iptables-wrapper

- CHANGES.md
> Prepare to release v0.2.0

- src/hostnet_test/test_http.ml
> test: check that the HTTP proxy doesn't duplicate host headers

- src/hostnet_test/test_http.ml
> test: check the HTTP proxy handles HEAD requests

- src/hostnet/slirp.ml
This will be helpful when debugging proxy connectivity issues.
> [stable] Capture traffic to/from HTTP(S) proxies

- src/hostnet/slirp.ml
This will be helpful when debugging proxy connectivity issues.
> Capture traffic to/from HTTP(S) proxies

- src/bin/main.ml
Previously we were limited to listening on one endpoint per service. This change allows us to, for example, listen once on Hyper-V for a VM and another time on a named-pipe for software on the Host.
> Allow multiple --port --introspection and --diagnostics arguments

- src/hostnet/hostnet_dns.ml
Previously the client could request a builtin name like `docker.for.mac.http.internal` and ask for both A and AAAA records. We would return the A record and then potentially timeout the AAAA response if the upstream DNS server is missing or unresponsive. This manifests, for example, as very slow HTTP
transactions.
This patch claims all RRs for the "builtin" names. If we don't actually have an RR (e.g. no IPv6 address) then we return NXDomain and don't attempt to forward the request upstream.
> dns: return NXDomain for a builtin where we don't have RRs

- src/bin/main.ml
Previously we only supported connecting to Hyper-V sockets because
old version of Windows would sometimes bluescreen while accepting
connections. All supported versions of Windows 10 work correctly
so this patch defines a new URL scheme
```
hyperv-listen://vmid/serviceid
```
which runs a standard listen / accept loop.
> Add support for listening on Hyper-V sockets

- src/hostnet/hostnet_http.ml
- src/hostnet/hostnet_http.mli
- src/hostnet/slirp.ml
- src/hostnet/slirp.mli
- src/hostnet_test/test_http.ml
> test: check the transparent proxy respects excludes

- src/hostnet_test/test_http.ml
This test starts an origin server on localhost which will respond with a minimal HTTP/1.0 response, with no connection-length or transfer-encoding. A client connects to the builtin HTTP proxy on port 3128 and requests a URI on the origin server. The test requires the body to be proxied correctly by the proxy (i.e. all data up to EOF should be transferred)
Tests #361
This PR is built on top of #366, only the last patch is relevant.
> test: check the proxy respects Connection: close from origin servers

- src/hostnet/hostnet_dns.ml
- src/hostnet/hostnet_icmp.ml
- reduce spam from ICMP traffic on the host
- reduce spam from DNS lookups of "builtin" names
> Reduce log spam

- src/bin/main.ml
This patch adds the argument
```
--gc-compact-interval <seconds>
```
which, if present, starts a background timer which invokes `Gc.compact` every <seconds> and then logs some statistics.
This patch also adds a handler for `SIGUSR1` to allow the heap to be immediately compacted.
> Allow the heap to be compacted regularly

- src/hostnet/hostnet_http.ml
- src/hostnet_test/test_http.ml
A simple HTTP 1.0 response is
```
HTTP/1.0 200 OK\r
\r
<EOF>
```
If an HTTP response has no Connection: header then:
- if HTTP 1.0 we assume Connection: close
- if HTTP 1.1 we assume Connection: keep-alive
> HTTP: HTTP/1.0 defaults to connection: close

- go/pkg/vpnkit/connection_unix.go
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>
> go: support linux

- src/bin/main.ml
Previously on Windows we used the 9P port filesystem server URL for both the 9P server control plane and the data plane (connected to vpnkit-forwarder).
Unfortunately now we switch to VM -> host connection for the 9P server, the command-line doesn't contain the VM's GUID so port forwarding is broken.
This patch uses the existing --vsock-path / --port-forwards argument to configure the data plane on both Windows and Mac. For backwards compatibility it still supports a raw path, but now also supports
- file:///foo/bar
- hyperv-connect://vmid/serviceid/
> Add a new `--port-forwards` command-line option

- c/vpnkit-9pmount-vsock/log.h
- c/vpnkit-tap-vsockd/log.h
Previously we would log to stdout.
> vpnkit-{tap,9pmount}-vsock: log to stderr

- go/Dockerfile.dial-example
- go/Makefile
- go/pkg/vpnkit/dialer_linux.go
Unfortunately this wasn't being built by travis, so this PR attempts to fix that too.
> Fix build of go/pkg/vpnkit on Linux

- src/hostnet/hostnet_udp.ml
If two UDP datagrams arrive from the same port, both threads will
contend for the `new_flow_lock` mutex which is *after* the check to see
if a hashtable record exists. Therefore both threads will create
a hashtable entry for the same flow and bind 2 sockets.
We wish to keep the fast-path (already-established connections) fast,
so rather than hold the mutex for the whole function we instead
re-check the hashtable after acquiring the mutex.
> Udp: avoid possible duplicate flow

- src/hostnet/hostnet_udp.ml
The lower part of the stack does maintain references to the packets
(e.g. the .pcap capturing layer) so it's important not to have each
packet share the same buffer.
This patch also makes it clearer that `loop` is processing packets
from the outside going into the virtual network, and the receive
buffer is private.
> UDP: copy packets before forwarding

- go/pkg/libproxy/network_proxy_test.go
The client is supposed to send UDP to the "frontend" of the IP proxy
to check the proxy isn't stopped when it tries to forward to a "backend"
which doesn't exist yet.
> test: fix TestUDPWriteError

- go/pkg/libproxy/multiplexed.go
Discarding data resynchronises the stream so we can continue.
> go: mux: if we discard data, don't fail afterwards

- CHANGES.md
- src/bin/main.ml
- src/hostnet/slirp.ml
> Update CHANGES.md for v0.3.0

- go/pkg/controller/controller.go
- go/pkg/controller/controller_test.go
The current implementation of the Kubernetes controller doesn't handle update properly. 
For instance, if I deploy an nginx and expose it:
```
kubectl run --image nginx nginx
kubectl expose deploy nginx --port 80 --type=NodePort
```
Then after change the port using `kubectl edit svc nginx`.
Two ports are now opened. The original port should be close.
> When calling OnUpdate, Kubernetes controller now closes removed ports

- go/pkg/vmnet/vmnet.go
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>
alternative to #471 
@djs55
> vmnet: remove dhcp pcap

- go/pkg/vmnet/vmnet.go
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>
sorry #472 caused regression
@djs55
> fix regression in "vmnet: remove dhcp pcap" (#472)

- Dockerfile
- repo/darwin/packages/dev/hvsock.2.0.0/opam
- vpnkit.opam
> Fix Dockerfile

- go/pkg/libproxy/expose_port.go
- go/pkg/libproxy/loopbackconn.go
- go/pkg/libproxy/multiplexed.go
- go/pkg/libproxy/udp_encapsulation.go
- go/pkg/vpnkit/control/control.go
- go/pkg/vpnkit/forward/unix_unix.go
- go/pkg/vpnkit/forward/vmnet_darwin.go
- go/pkg/vpnkit/http.go
- go/pkg/vpnkit/port.go
Most important is about json serialisation.
ListExposed() returns now an empty list instead of nil.
> Various linter error fixes

- go/Gopkg.lock
- go/Gopkg.toml
- go/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock.go
- go/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock_fallback.go
- go/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock_linux.go
- go/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock_windows.go
- go/vendor/github.com/linuxkit/virtsock/pkg/hvsock/zsyscall_windows.go
- go/vendor/github.com/linuxkit/virtsock/pkg/vsock/vsock.go
- go/vendor/github.com/linuxkit/virtsock/pkg/vsock/vsock_linux.go
Docker Desktop vendors vpnkit master + virtsock master and it works like a charm. Let's synchronize it here also.
> Upgrade linuxkit/virtsock vendoring

- MAINTAINERS
I am definitely not the right person for the Ocaml part but I hope to be useful for the CI and Go parts.
Thanks!
> Add guillaumerose to maintainer list

- go/pkg/libproxy/udp_encapsulation.go
- go/pkg/vpnkit/forward/vmnet_darwin.go
Signed-off-by: Simon Ferquel <simon.ferquel@docker.com>
> fix mac build

- .circleci/config.yml
- Dockerfile
- Makefile.darwin
- repo/licenses/LICENSE.vpnkit.0.2.0
This one has Apple Silicon support!
A few package pins are necessary (temporarily)
> Update OCaml to 4.12

- src/hostnet/slirp.ml
Previously we used the wall clock via `Unix.gettimeofday()` to compute the idle time for "endpoints" (remote destinations). When a laptop wakes from sleep, the wall clock jumps forward and suddenly all the endpoints are idle and the connections are dropped.
This patch switches to a monotonic clock which is driven by a CPU counter. The counter is paused while the computer sleeps and therefore does not jump forwards on wake.
This patch also adds a log message whenever an "endpoint" is deleted, to make debugging problems easier.
> Base idle time calculations on a CPU counter, not a wall clock

- repo/win32/packages/upstream/config-file.1.2/url
- repo/win32/packages/upstream/ounit.2.0.8/url
> ounit: correct download URL

- scripts/licenses.ml
> licenses: add dune.2.9.2

- .circleci/config.yml
- appveyor.yml
- dune
- scripts/licenses.ml
> licenses: include name and license type (e.g. SPDX)

- go.mod
Changed `1.16` to `1.17` then did a `go mod tidy`.
> Update go mod to 1.17

- src/hostnet/hostnet_http.ml
Previously we explained more in the body, but this is usually ignored by tools like docker pull.
The reason phrase is usually printed, so write some custom text there (rather than "Service_unavailable")
Before:
```
dave@m1 vpnkit % docker pull registry-1.docker.io:1235/old:error
Error response from daemon: Get "https://registry-1.docker.io:1235/v2/": Service Unavailable
```
After:
```
dave@m1 vpnkit % docker pull registry-1.docker.io:1234/new:error
Error response from daemon: Get "https://registry-1.docker.io:1234/v2/": unable to connect to 34.237.244.67:1234. Do you need an HTTP proxy?
```
> http: send more informative reason phrases in errors

- MAINTAINERS
- scripts/licenses.ml
@fredericdalleau has been doing great work investigating regressions in the TCP stack's SYN handling.
> Add Frederic as a maintainer

- .circleci/config.yml
- scripts/licenses.ml
- src/dns_forward/dune
- src/dns_forward_test/flow.ml
- src/dns_forward_test/rpc.ml
- src/dns_mirage/dns_resolver_mirage.ml
- src/fs9p/fs9p.ml
- src/fs9p/fs9p_error.mli
- src/fs9p/vfs.ml
- src/fs9p/vfs.mli
- src/hostnet/cohttp_mirage_io.ml
- vpnkit.opam
macOS 10.15 is Catalina+ and matches the current Docker Desktop limits https://docs.docker.com/desktop/install/mac-install/
> circleci: bump to latest xcode, macOS 10.15

- Makefile
- scripts/licenses.ml
In particular we would like https://github.com/ocaml/ocaml/pull/10549 to make diagnosing https://github.com/docker/for-mac/issues/6472#issuecomment-1240798168 easier.
> ocaml: bump to 4.14

- src/bin/logging.ml
Previously the logging was async, so there could be logs in the buffer when the program quits (especially if it fails unexpectedly)
> logger: guarantee to flush the logs on exit

- Makefile
- README.md
- scripts/licenses.ml
- The makefile has two 'depends' targets, and it was ignoring the first one
- also requires `dylibbundler`
- got some license errors so i fixed them
> tweak some of the instructions for setting up on a new machine

- go/pkg/libproxy/multiplexed.go
The `sendWindowUpdate` function acquires the `writeMutex` and writes to the channel. Since `Accept()` holds the `metadataMutex`, this prevents processing other connections.
In all other places we carefully drop the metadata mutex before writing. Accept was an oversight.
> go: libproxy: don't hold the metadata mutex while writing

- go/pkg/vmnet/vmnet.go
1. responses can be broadcast rather than unicast
2. check for the operation type and transaction ID
> vmnetd: fix DHCP response parser

- .github/workflows/bin-image.yml
- Dockerfile
- docker-bake.hcl
Based off: https://github.com/moby/moby/blob/master/.github/workflows/bin-image.yml
> Add GHA workflow to build image
