- src/com.docker.slirp.exe/src/main.ml
The recent change to avoid completely failing when the connect failed
neglected to close the socket. This results in a slow leak of sockets
(and 2 threads per socket) while the VM is offline.
> com.docker.slirp.exe: on failure, close the socket

- src/com.docker.slirp/src/connect.ml
Previously we mapped exposed ports on the host (localhost) to vsock ports
in the range 0x10000-0x20000 for TCP and 0x20000-0x30000 for UDP. Unfortunately
this approach doesn't work for Hyper-V sockets since we have to manually
register GUIDs in the Windows registry. This patch switches to a different
scheme where there is one well-known port forwarding port, we connect to it
and write a header describing the ultimate destination, and the proxy redirects
us. This should probably be replaced with a SOCKs proxy.
> com.docker.slirp: connect to a single well-known port forwarding port

- src/com.docker.slirp/src/connect.ml
The hyperkit virtio-vsock path has recently moved to the container folder.
Signed-off-by: Gaetan de Villele <gdevillele@gmail.com>
Imported-by: David Scott <dave.scott@docker.com>
> com.docker.slirp: fixed path for @connect socket

- src/com.docker.slirp.exe/src/main.ml
When we're connecting to the VM, don't bother logging each individual
connection rejection -- it's not particularly useful information.
> com.docker.slirp.exe: remove AF_HYPERV connection spam

- packages/tcpip.999/opam
opam is complaining:
[WARNING] At ~/kits.opam/packages/tcpip/tcpip.999/opam:50:9:
Version constraint (>= 1.1.0) no longer allowed in optional dependency (ignored).
Use the 'conflicts' field instead.
As suggested turn the >= 1.1.0 version constraint into a conflict with < 1.1.0.
Signed-off-by: Ian Campbell <ian.campbell@docker.com>
> Move mirage-net-unix version constraint to conflicts

- src/hostnet/lib/dns_forward.ml
- src/hostnet/lib/dns_forward.mli
- src/hostnet/lib/sig.ml
- src/hostnet/lib/slirp.ml
Users will no longer have to construct additional modules and records which won't be used by Dns_forward.
> Have Dns_forward operate on ipv4 and udpv4 modules, not an entire stack

- src/hostnet/lib/dns_forward.ml
- src/hostnet/lib/dns_forward.mli
- src/hostnet/lib/slirp.ml
If the first upstream DNS server fails to respond then the guest will retry, today we would forward the retry to the same server, whereas on a native system it would try the next server in `resolv.conf`. This makes vpnkit more susceptible to errors due to a flakey upsteam server.
To resolve this keep track of in progress DNS requests and if we observe a reuse of a transaction id round-robin through the upstream servers instead of reusing the first.
> Fallback to secondary DNS servers upon retries

- src/com.docker.slirp/_oasis
- src/com.docker.slirp/opam
- src/com.docker.slirp/src/main.ml
This is the maximum on OSX, while the default is 256 which can be quite quickly
exhausted by parallel network traffic.
Also plumb through as a command line option.
Signed-off-by: Ian Campbell <ian.campbell@docker.com>
> com.docker.slirp: Bump nofile rlimit to 10240

- src/hostnet/lib/slirp.ml
Currently if the peer sends TCP traffic to us on port 53 then we process it. If the peer sends TCP traffic to us on other ports then we try to make a connection on on the *outside* network to the IP from the *inside* network. This seems wrong because
-  the internal IP is arbitrary and only valid on the inside network, so we should only use it on the inside network
- the peer has deliberately directly addressed us, so we should treat it as a connection request to us and respond as such.
This PR redirects connections sent to the gateway IP (i.e. "bound" to the virtual interface inside vpnkit) to 127.0.0.1 on the host running vpnkit. In the context of Docker for Mac this would allow services to be run on the host and then accessed from a suitably privileged container (`--privileged …
> Send TCP addressed to us, to us rather than to someone else

- src/com.docker.slirp/src/bind.ml
- src/hostnet/lib/forward.ml
- src/hostnet/lib/port.ml
- src/hostnet/lib/port.mli
- src/hostnet/lib/sig.ml
On some platforms (at least Windows) accessing ports via `localhost` is very slow because the address `::1` will be tried first and will be allowed to timeout. This patch generalises the port bindings a little, allowing a single user-requested binding to be mapped to a list of listening sockets. When the user requests an address `0.0.0.0` or `127.0.0.1` we perform a best-effort bind to `::1` also to speed up accesses on these IPv6 platforms.
> When binds include localhost, try to bind ::1 as well

- opam/darwin/packages/dev/tcpip.999/url
Also known as 879b0fc68d2d44f5c6317f033ac50ffcc3d4277f
The backport is here:
https://github.com/djs55/mirage-tcpip/commit/0da78c96ab359252e473cd3c9e039680c6fb462e
In particular this avoids `Console.log_s` which won't work if we're using
`libuv` (or anything other than `Lwt_main.run` and `Lwt_unix`)
Related to #66 
> Backport mirage-tcpip "Use Logs library for logging"

- src/hostnet/lib/slirp.ml
TCP connections sent to our IP are normally forwarded to the host,
except for port 53 (DNS) which is forwarded to an upstream DNS
server.
Previously we checked whether a connection was "for us" by comparing
the IP destination to our IP. If a connection was for port 53 we would
then rewrite the IP destination but we failed to reconsider whether
this new IP was ours or not. This meant that we always forwarded TCP
on 53 to localhost by mistake.
This patch makes the "is connection for us" decision into a
function `for_us` and re-evaluates it when the destination IP may have
changed.
This fixes a bug introduced in a56356fd427870f7f3679b8dc9db6f403ea394db
> hostnet: fix TCP DNS (required when UDP responses are truncated)

- src/com.docker.slirp.exe/Makefile
- src/com.docker.slirp.exe/src/depends.ml.in
- src/com.docker.slirp.exe/src/main.ml
- src/com.docker.slirp/Makefile
- src/com.docker.slirp/src/depends.ml.in
- src/com.docker.slirp/src/main.ml
To make understanding bug reports easier, the log output will now contain the versions of
- `uwt`
- `hvsock`
- `hostnet`
> On startup log subcomponent versions

- opam/win32/packages/dev/hvsock.0.9.0/files/send-recv.patch
- opam/win32/packages/dev/hvsock.0.9.0/opam
This prevents returning SOCKET_ERROR as a number of bytes in the case
that WSAGetLastError() returns 0 (which it has been observed to do with
Hyper-V sockets)
> hvsock.0.9.0: add not-yet-released patch

- circle.yml
- src/com.docker.slirp.exe/src/main.ml
- src/com.docker.slirp/src/main.ml
- src/hostnet/lib/dns_forward.ml
- src/hostnet/lib/dns_forward.mli
- src/hostnet/lib/host_lwt_unix.ml
- src/hostnet/lib/host_uwt.ml
- src/hostnet/lib/sig.ml
- src/hostnet/lib/slirp.ml
- src/hostnet/lib/slirp.mli
- src/hostnet/lib/tcpip_stack.ml
- src/hostnet/lib/tcpip_stack.mli
- src/hostnet/lib_test/main.ml
The second commit is the interesting one. Its commit log:
In #38 I attempted to address the problem of flakey upstream DNS by
round-robinning DNS retries (detected via the DNS ID field), replicating the
fallback behaviour a client which has been given multiple entries in
resolv.conf despite only providing then with a single entry.
However this turns out to have been insufficient because not all client side
resolvers reuse the DNS ID on retry, so we do not see those retries as such and
send them to the primary upstream DNS a second time.
To address this create a second IP end point (on the same underlying device, so
essentially an IP alias)  and expose it to the client (via DHCP) as a second
DNS server which forwards to the secondary upstream DNS server and revert most
of #38 such that for …
> Add a secondary dns forwarder IP

- src/com.docker.slirp.exe/src/main.ml
- src/com.docker.slirp/src/main.ml
The 9P server used to control port forwarding emits some particularly
spammy and not terribly useful debug messages. This patch suppresses
these by setting the minimum level to `Info` for the 9P messages.
> com.docker.slirp: remove 9P log spam

- src/com.docker.slirp.exe/src/connect.ml
- src/com.docker.slirp.exe/src/connect.mli
- src/com.docker.slirp.exe/src/main.ml
- src/com.docker.slirp/src/connect.ml
- src/com.docker.slirp/src/connect.mli
- src/com.docker.slirp/src/main.ml
Every forwarded connection consumes resources:
- the accepted connection on the host
- the `virtio-vsock` or `AF_HYPERV` forwarded connection to the VM
- the accepted connection in the VM
- the forwarded connection in the VM
We've already bumped the maximum number of fds in various places, so now the bottleneck is the `virtio-vsock` or `AF_HYPERV` connection to the VM. We would like to avoid hitting this limit because it will cause the docker socket forward to fail too.
This PR adds code to support an upper limit to the number of supported concurrent connections forwarded into the VM. By default there is no limit, but a command-line `--max-connections` allows it to be set to some concrete value. When the limit is hit, incoming connections are closed, matching the behaviour of `libuv` when …
> Allow the max concurrent forwarded connections to be configured

- src/com.docker.slirp.exe/src/main.ml
- src/com.docker.slirp.exe/src/resolv_conf.ml
- src/com.docker.slirp.exe/src/resolv_conf.mli
- src/com.docker.slirp/src/resolv_conf.ml
- src/hostnet/_oasis
- src/hostnet/lib/resolver.ml
- src/hostnet/lib/resolver.mli
- src/hostnet/lib/sig.ml
- src/hostnet/lib/slirp.ml
- src/hostnet/lib_test/main.ml
- src/hostnet/lib_test/resolver_test.ml
If someone writes the key
com.docker.driver.amd64-linux/slirp/dns
with \n-separated lines of the form
a.b.c.d
a.b.c.d#e
then these will override the default host DNS servers. If the key is deleted
then the original behaviour is restored (i.e. on Mac read /etc/resolv.conv
and on Windows use the command-line or 127.0.0.1:53)
This means that, for example, a UI would be able to choose the upstream
DNS server without the VM noticing the change. It also lets us separate the
detection of upstream DNS logic (which might use lots of platform-specific
magic) from the DNS forwarder itself-- we can keep the bulk of this code
pure and isolate the platform specific part using the database for communication.
> Monitor the database for upstream DNS server overrides

- src/com.docker.slirp/src/resolv_conf.ml
We currently read all the 'nameserver' entries out of `resolv.conf`,
including the IPv6 and IPv4 entries.  However, the forwarding logic
in slirp does not handle the IPv6 case yet (primarily due to a lack
of testing), and so a user with an IPv6 resolver as the first entry
will have forwarding failures.
This patch filters for IPv4 resolvers to work around the issue so that
if the `resolv.conf` has at least one IPv4 server, it will get picked
up and used.  This is the minimal patch: we do need to support IPv6
forwarding as well but that will be a bigger change.
Reported in docker/for-mac#9.
Signed-off-by: Anil Madhavapeddy <anil@docker.com>
> Filter IPv6 resolvers from /etc/resolv.conf until we have V6 forwarding

- src/hostnet/lib/dns_forward.ml
- src/hostnet/lib/dns_forward.mli
- src/hostnet/lib/slirp.ml
- filter IPv6 DNS servers in the core library so it's easier to test; and to ensure covers both the `/etc/resolv.conf` path and the DNS-servers-in-database-keys path
- share the same primary/secondary server choosing logic between UDP and TCP: this fixes TCP DNS to the secondary IP by forwarding it to the second nameserver correctly
> More DNS fixes

- Makefile
- src/hostnet/_oasis
- src/hostnet/lib_test/main.ml
These tests set up a local server and then use the Mirage client to connect and send 1KiB, 1MiB and 1GiB through each connection, with up to 32 separate connections.
These work fine on OSX, but they're untested on Windows. There might be a problem running them from the CI on appveyor because of the Windows firewall -- if the tests timeout this is probably why.
> Add some TCP loopback connection tests

- src/com.docker.slirp/src/main.ml
- src/hostnet/_oasis
- src/hostnet/lib/dns_forward.ml
- src/hostnet/lib/dns_forward.mli
- src/hostnet/lib/slirp.ml
- src/hostnet/lib/slirp.mli
- src/hostnet/lib/tcpip_stack.ml
- src/hostnet/lib/tcpip_stack.mli
- src/hostnet/lib_test/main.ml
- src/hostnet/opam
This PR generalises the mechanism to include a list of server IPs rather than a single primary and single secondary.
The PR also adds another 8 virtual DNS IPs. Hopefully this will work better for people who have more than 2 real DNS servers -- this probably happens when connecting to a VPN, where you are likely to gain additional servers.
Fixes #99
> Support more than 2 physical DNS servers

- src/com.docker.slirp/src/main.ml
- src/hostnet/_oasis
- src/hostnet/lib/dns_forward.ml
- src/hostnet/lib/host_lwt_unix.ml
- src/hostnet/lib/host_uwt.ml
- src/hostnet/lib/hosts.ml
- src/hostnet/lib/hosts.mli
- src/hostnet/lib/sig.ml
- src/hostnet/lib_test/hosts_test.ml
- src/hostnet/lib_test/main.ml
This PR allows users to edit `/etc/hosts` (or the Windows equivalent, defender-permitting) and then resolve the names inside the VM as well as on the host.
The patches break down into:
- Parse `/etc/hosts` (or the Windows equivalent) and keep a cache of the values found therein. In case the path is not quite as universal as hoped, it can be overridden by a command-line argument `--hosts <path>`
- When a DNS request is received, first lookup `A` and `AAAA` requests in our cache. Reply with the any cache hit; otherwise fall back to upstream servers.
- A test for the DNS lookup through the cache
- A test for the `/etc/hosts` file parser
Note I tried using the `Fs_event` API from `libuv`/`uwt` but I couldn't get it to emit more than one event, so this PR falls back to polling every 5s.
> DNS: serve up entries from /etc/hosts

- src/hostnet/lib/tcpip_stack.ml
This reverts commit 6ea1b3809586748f0322651fa7704e7372d87256.
Unfortunately the short lease time has exposed a problem with the
mirage-tcpip stack, which we need to fix before we can do this.
> Revert "dhcp: set the lease time to 10s"

- src/com.docker.slirp/Makefile
- src/com.docker.slirp/pkg/pkg.ml
We substitute %%VERSION%% with the $(git rev-parse HEAD), and attempt
to substitute the %%*_PINNED%% properly.
> Attempt to fix watermarking

- src/hostnet/_oasis
- src/hostnet/lib/constants.ml
- src/hostnet/lib/forward.ml
- src/hostnet/lib/host_lwt_unix.ml
- src/hostnet/lib/host_uwt.ml
The maximum UDPv4 datagram size is 65507 (which is IPv4 datagram (65535) - IPv4 header(20) - UDPv4 header(8)). Previously the code assumed the size was limited to the MTU of the ethernet network.
Furthermore, if we get a "partial" `recvfrom` (which means the packet was too big for the buffer) then log and continue. Previously we would shut down the listening thread which caused UDP forwarding to stop working.
Related to [docker/for-mac#674]
> Increase UDP datagram limits

- src/hostnet/lib/dns_forward.ml
- src/hostnet/lib/host_lwt_unix.ml
- src/hostnet/lib/host_uwt.ml
- src/hostnet/lib/sig.ml
- src/hostnet/lib/slirp.ml
Previously we would hold open a UDP NAT rule (and associated
socket) for 60s. This could waste a lot of sockets for DNS-heavy
workloads.
This patch closes the socket and removes the rule as soon as the
response is received. If the response is never received then the
GC will kick-in as before.
This is a short term patch before the next DNS rewrite.
> For DNS, make the UDP NAT rules one-shot

- opam/darwin/packages/dev/tcpip.999/url
- src/com.docker.slirp/src/bind.ml
- src/com.docker.slirp/src/connect.ml
- src/com.docker.slirp/src/connect.mli
- src/com.docker.slirp/src/main.ml
- src/hostnet/lib/host_lwt_unix.ml
- src/hostnet/lib/host_uwt.ml
- src/hostnet/lib/sig.ml
- src/hostnet/lib_test/main.ml
Previously we would cap the total number of connections we would `accept` and forward into the VM-- this still allowed us to hit system limits by forwarding regular connections out of the VM (particularly on OSX). This PR extends the connection limiting code to all connections, irrespective of direction.
> Extend the connection limit

- circle.yml
- opam/darwin/packages/dev/charrua-core.999/url
- src/hostnet/lib/filter.ml
- src/hostnet/lib/filter.mli
- src/hostnet/lib/tcpip_stack.ml
Unfortunately switching the client from udhcpc to dhcpd causes a
problem because by default dhcpd will send a "duid" which charrua
doesn't recognise corresponds to the MAC address in the static
map. Since vpnkit currently only expects one client anyway,
switch to a dynamic range containing one element.
> dhcp: remove the static map, allow exactly one dynamic IP

- src/com.docker.slirp/src/main.ml
- src/hostnet/lib/host_lwt_unix.ml
- src/hostnet/lib/host_uwt.ml
- src/hostnet/lib/slirp.ml
- src/hostnet/lib/vmnet.ml
This is more flexible than the command-line which was being hardcoded
elsewhere. Note the command-line is still parsed but the value is ignored.
The help for the argument explains the path to the database key.
> Allow connection limit to be set via the database

- src/hostnet/lib/host_uwt.ml
Previously there was a missing interaction between the connection-tracking
PR and the one-shot DNS PR: when a one-shot DNS UDP rule was cleaned up,
the connection was leaked. This patch fixes the leak.
> dns: when closing one-shot connections, deregister them

- src/com.docker.slirp/src/main.ml
- src/hostnet/_oasis
- src/hostnet/lib/capture.ml
- src/hostnet/lib/capture.mli
- src/hostnet/lib/host_lwt_unix.ml
- src/hostnet/lib/host_uwt.ml
- src/hostnet/lib/sig.ml
- src/hostnet/lib/slirp.ml
- src/hostnet/lib/slirp.mli
- src/hostnet/lib/tcpip_stack.ml
- src/hostnet/lib/tcpip_stack.mli
This PR allows packet filters to be defined statically as follows:
```ocaml
open Capture.Match
(* Capture 1 MiB of all traffic *)
add_match ~t ~name:"all.pcap" ~limit:mib all;
(* Capture 256 KiB of DNS traffic *)
add_match ~t ~name:"dns.pcap" ~limit:(256 * kib)
(ethernet @@ ipv4 () @@ ((udp ~src:53 () all) or (udp ~dst:53 () all) or ((tcp ~src:53 () all) or (tcp ~dst:53 () all))));
```
The most recent packets (up to the configured limit in bytes) matching each filter are stored, and can be downloaded over 9P as follows:
```
<favourite 9P util> read capture/dns.pcap
```
The DNS filter should be useful for debugging the future DNS resolver rewrite.
> Add bounded-size packet recording

- opam/darwin/packages/dev/tcpip.999/url
- src/_oasis
- src/hostnet/slirp.ml
This pulls in the patches from [mirage/mirage-tcpip#193] so we're closer to the APIs provided by tcpip.2.8.1 (although we're not quite there yet)
> Update to new mirage-tcpip ICMPv4 interface

- src/hostnet/slirp.ml
Previously we added APIs in a custom fork of mirage-tcpip
so we could customise the source address of the IP datagrams. We don't
need to do this now that we use multiple TCP/IP instances.
With this patch the code works against upstream tcpip.2.8.1
> Use upstream APIs `allocate_frame` and `Udpv4.write`

- src/hostnet/capture.mli
- src/hostnet/dns_forward.ml
- src/hostnet/dns_forward.mli
- src/hostnet/sig.ml
- src/hostnet/slirp.ml
Previously we would only see the VM half of UDP DNS transactions, since `module Capture` is placed inline on the virtual ethernet link. This PR injects datagrams corresponding to UDP DNS activity on the host directly into the `module Capture` so the debug traces will show the query and response from the upstream server too.
Now that the DNS capturing is working well, the default log level of the `Dns_forwarder` can be raised from `Debug` to `Info`.
> Capture both sides of DNS transactions

- src/bin/main.ml
- src/hostnet/dhcp.ml
- src/hostnet/dhcp.mli
- src/hostnet/slirp.ml
- src/hostnet/slirp.mli
- src/hostnet_test/slirp_stack.ml
- src/ofs/active_config.ml
- src/ofs/active_config.mli
Previously the DHCP server hardcoded the domain name to `local`. This PR allows the domain name to be overriden via the database key `slirp/domain`.
Note this PR also contains a bug fix to the very similar search domain override mechanism. Ideally I'd add a unit test for this but it's a bit tricky using the built-in DHCP client in `tcpip.2.8.0` which doesn't seem to expose the information.
> Allow the DHCP server domain name to be overriden

- src/Makefile
Previously the `mv main.native` simply moved the symlink to the binary
into the staging area. Using `cp main.native` means the symlink should
be followed and the contents copied instead.
> Include the Mac binary in the artefact, not a dangling symlink

- src/hostnet/slirp.ml
@samoht observed a recent test run generated 227MiB of log files, mostly "Errors" explaining that the remote server refused a connection (as it is totally at liberty to do)
This PR:
- increases minimum debug level to Info (was debug)
- downgrades some "errors" to "debug"
> Reduce spammy logging

- appveyor.sh
- circle.yml
Previously the tests became disabled in CI when we moved from installing
hostnet via `opam install -t` to a simpler oasis/Makefile.
This patch adds `make test` to circle.yml and appveyor.sh
> Re-enable testing

- src/hostnet/host_lwt_unix.ml
- src/hostnet/host_uwt.ml
Previously the `listen` loop allocated a buffer and called `recvfrom`
to read a UDP datagram. The flow callback was called asynchronously
with a reference to this buffer, so the next `recvfrom` could overwrite
the contents.
This patch uses a fresh buffer per `recvfrom` which avoids accidentally
overwriting a previous packet.
> Udp: fix packet overwriting bug in listen

- Makefile
Unfortunately it's not a fatal error for an artifact to be missing.
Previously we placed the .tgz file in .. believing it to be relative
to the -C src directory provided to tar. This patch places the .tgz
in the root of the tree.
> CircleCI: attempt to fix artifact upload

- src/hostnet/host_lwt_unix.ml
- src/hostnet/host_uwt.ml
Previously we used `Ipaddr.t` values everywhere which allowed both v4 and v6, but we always used functions like `Uwt.Tcp.init ()` which only works for v4 leading to an `EINVAL` on `connect`. This PR chooses the correct protocol family for the address.
This PR also corrects log lines which were previously hardcoded to say things like `Socket.TCP4`.
> Use the protocol family which matches the address

- src/hostnet/host_uwt.ml
Previously we deregistered the connection and then called `Lwt.fail`.
Since we're in the middle of an `Lwt.catch`, control passes to the
exception handler which calls `deregister_connection` again. In most
cases this logs a benign error but it some cases we might deregister
some other connection which could cause the connection limiting to
underestimate the total number of active connections.
> Uwt: remove an unnecessary `deregister_connection`

- src/_oasis
- src/hostnet_test/forwarding.ml
- src/hostnet_test/main.ml
- src/hostnet_test/main_lwt.ml
- src/hostnet_test/main_uwt.ml
- src/hostnet_test/nat.ml
- src/hostnet_test/suite.ml
Previously the tests could block forever, particularly infuriating as
this locks the appveyor CI slot for 1hr. All the tests should execute
within 10s, except the max connections one which has been given a 4
minute maximum.
> test: add explicit 10s timeouts for most of the tests

- README.md
This describes the minimal command-line arguments needed to start
`com.docker.slirp` and to connect `com.docker.hyperkit` to it.
> README.md: add brief notes on using with hyperkit

- src/bin/main.ml
- src/hostnet/arp.ml
- src/hostnet/forward.ml
- src/hostnet/host_uwt.ml
- src/hostnet/hostnet_udp.ml
- src/hostnet/mux.ml
- src/hostnet/slirp.ml
- src/hostnet/vmnet.ml
- src/hostnet_test/suite.ml
- src/ofs/active_list.ml
The goal is to remove as many "expected" logs which are emitted with severity "error", so it becomes possible to grep the logs for "ERROR" and see something meaningful.
Fixes #108
> Trim or demote spammy errors

- opam/darwin/packages/dev/dns.999/descr
- opam/darwin/packages/dev/dns.999/opam
- opam/darwin/packages/dev/dns.999/url
- opam/darwin/packages/local/slirp.local/opam
- opam/win32/packages/dev/dns.999
This is a port of
https://github.com/mirage/ocaml-dns/pull/109
> Add a patch to ocaml-dns to fix the resource-record parsing

- Dockerfile
- Makefile
- opam
- scripts/common.sh
- default `make` targets now work on Linux (should fix build error https://travis-ci.org/ocaml/opam-repository/builds/178430928)
- `Dockerfile` refreshed to new repo structure
- remove `ounit` from `opam`
- `alcotest` is a test dependency in `opam`
> Improve Makefile, Dockerfile and opam

- src/bin/bind.ml
- src/bin/connect.ml
- src/bin/main.ml
- src/hostnet/capture.ml
- src/hostnet/dhcp.ml
- src/hostnet/filter.ml
- src/hostnet/forward.ml
- src/hostnet/host_lwt_unix.ml
- src/hostnet/host_uwt.ml
- src/hostnet/hosts.ml
This PR bumps the minimum logging threshold from `Debug` to `Info`. Previously the Mac ASL reporter would omit `Debug` messages anyway, but they would still be printed on Windows. Hopefully this makes Windows as quiet as the Mac.
> Reduce log spam even further

- src/hostnet/host_lwt_unix.ml
- src/hostnet/host_uwt.ml
The Unix.inet_addr type includes both IPv4 and IPv6. When we send
traffic over UDP we first bind the socket to "any". Previously we
used the value `Unix.inet_addr_any` but this is IPv4-only. This patch
selects either `Unix.inet_addr_any` or `Unix.inet6_addr_any`.
> Use the correct Unix.inet_addr matching the PF in bind

- opam
We need to use the new versioned `Lwt_unix.bind` interface in future.
> opam: depend on lwt < 3.0.0

- src/hostnet/hosts.ml
- src/hostnet_test/hosts_test.ml
- src/hostnet_test/main_lwt.ml
- src/hostnet_test/main_uwt.ml
- src/hostnet_test/suite.ml
Previously we would fail to parse lines which included extra aliases, for example we would fail to parse:
```
127.0.0.1 localhost mylocalhostalias
```
This PR fixes the parser and adds a test.
> Fix parsing of /etc/hosts

- src/bin/connect.ml
The Lwt_preemptive and Uwt_preemptive thread pools have a fixed
maximim size, typically 4. The main TCP/IP stack needs to be able
to acquire one of these workers or else it blocks. This patch
stops using `detach` in the port forwarding path, so that incoming
port forwards don't break the main network.
> Avoid using `detach` for port forwarding

- repo/darwin/packages/dev/mirage-types-lwt.2.8.999/descr
- repo/darwin/packages/dev/mirage-types-lwt.2.8.999/opam
- repo/darwin/packages/dev/mirage-types.2.8.999/descr
- repo/darwin/packages/dev/mirage-types.2.8.999/opam
- repo/darwin/packages/dev/mirage-types.2.8.999/url
- repo/darwin/packages/dev/tcpip.999/url
- repo/darwin/packages/local/slirp.local/opam
- repo/licenses/LICENSE.mirage-types-lwt.2.8.999
- repo/licenses/LICENSE.mirage-types.2.8.999
- repo/win32/packages/dev/mirage-types-lwt.2.8.999
- repo/win32/packages/dev/mirage-types.2.8.999
- src/bin/main.ml
- src/hostnet/capture.ml
- src/hostnet/filter.ml
- src/hostnet/sig.ml
- src/hostnet/slirp.ml
- src/hostnet/slirp.mli
- src/hostnet/vmnet.ml
- src/hostnet/vmnet.mli
- src/hostnet_test/slirp_stack.ml
This PR separates the MTU used for outgoing datagram traffic (for which we need to respect the Do Not Fragment bit) from the MTU used on the internal virtual ethernet link and bumps the latter to 8000. This should allow the TCP stack to use a larger segment size and to reduce the overhead per byte of payload.
This PR also allows the virtual ethernet MTU to be set via the database key `com.docker.driver.amd64-linux/slirp/mtu`
Note this PR references a port of https://github.com/mirage/mirage-protocols/pull/4 and https://github.com/mirage/mirage-tcpip/pull/288 but we need to do some rebasing work for the v3 release anyway.
> Increase the MTU on the virtual ethernet link

- src/hostnet/vmnet.ml
Historically this value from vmnet.framework was around 1550, or mtu + 50. This patch restores the link with the MTU.
Without this, some packets are erroneously truncated and dropped.
> Derive a `max_packet_size` from the MTU

- src/bin/main.ml
- src/hostnet/capture.ml
- src/hostnet/capture.mli
- src/hostnet/slirp.ml
- src/hostnet/slirp.mli
- src/hostnet_test/slirp_stack.ml
For debugging we maintain a fixed amount of captured traffic which can be accessed via diagnostic commands. Previously we would keep entire packets. This patch limits the capture to 128 bytes per packet which is enough for most headers (including, for example, enough for TCP stream analysis) but omits most of the payloads.
> Only capture the first 128 bytes of traffic

- repo/darwin/packages/dev/dns.999/url
This is a backport of
https://github.com/mirage/ocaml-dns/pull/129
onto the v0.18.1 stable branch used by vpnkit.
> Backport DNS parser pointer to pointer fixes

- src/hostnet/slirp.ml
Previously we collected a sample of general traffic for debugging but
this hasn't been particularly useful. This patch removes this generic
capture but leaves in the DNS-specific capture which is still useful.
> Capture less debug traffic

- .gitignore
- Makefile
- README.md
- appveyor.yml
- circle.yml
Previously the repo was called `vpnkit` but the artifact was called
`com.docker.slirp`. This patch renames the artifact `vpnkit`.
> Rename default artifact to match repository

- .merlin
- _oasis
- appveyor.yml
- opam
- src/bin/main.ml
- src/hostnet/dhcp.ml
- src/hostnet/dhcp.mli
- src/hostnet/frame.ml
- src/hostnet/slirp.ml
- src/hostnet/slirp.mli
- src/hostnet_test/slirp_stack.ml
Adds an optional bridge with mirage-vnetif. Also fixes a bug where ethernet frames were read with the `src`/`dst` fields swapped and adds a `.merlin` file to the project (this PR subsumes #187).
> Fix ethernet parsing bug, add l2 bridge

- src/bin/main.ml
- src/hostnet/slirp.ml
Packets are only routed to bridge if the ethernet frame dst/src do not match client/server side or broadcast. Each connection to vpnkit gets a new mac-address, so this also partially fixes #190. 
> Set bridge mode on by default

- src/bin/main.ml
- src/ofs/active_config.ml
- src/ofs/active_config.mli
Currently the configuration parameters are read from the "master"
branch. This patch factors out the branch name so it is only written
in one place and can be more easily changed.
> Allow the config database branch to be changed

- src/bin/main.ml
- src/hostnet/host_lwt_unix.ml
- src/hostnet/host_uwt.ml
- src/hostnet/sig.ml
Previously when we hit a connection limit we would not be able to produce any diagnostic output, hampering attempts to understand the failure.
This PR allows `server` instances to be exempted from the tracking and exempts both the `.tar` download and the 9P introspection interface.
> Exempt diagnostics from connection limits

- src/bin/bind.ml
- src/hostnet/forward.ml
- src/hostnet/host_lwt_unix.ml
- src/hostnet/host_uwt.ml
- src/hostnet/hostnet_udp.ml
- src/hostnet/sig.ml
Through the diagnostic interface we now see:
drwxrwxr-x ? root root 0 Jan 1 1970 udp:0.0.0.0:0 udp:192.168.65.2:51726-127.0.0.1:123
instead of
drwxrwxr-x ? root root 0 Jan 1 1970 udp:0.0.0.0:0
i.e. we see why a listening socket has been created. This will help understand connection leaks.
> Improve the connection tracking diagnostics

- src/bin/main.ml
- src/hostnet/hostnet_dns.ml
- src/hostnet/hostnet_dns.mli
- src/hostnet/sig.ml
- src/hostnet/slirp.ml
- src/hostnet_test/slirp_stack.ml
Previously we conflated the list of upstream servers to use, with whether to use them or the host resolver. This PR separates these into 2 separate configuration variables
- `slirp/resolver`: `host` means use the host resolver, any other string means use the upstream resolvers
- `slirp/dns`: the current upstream DNS servers
This simplifies the integration into D4D since we can have a background configuration watcher own the `slirp/dns` key and invite the user to change the mode via the `slirp/resolver` key.
This PR also tidies up the diagnostic pcap a little, but removing duplicated packets.
> Improve switching between DNS modes

- src/hostnet/dhcp.ml
See https://github.com/mirage/charrua-core/pull/48 for more discussion.
> don't add DHCP options with empty lists

- src/hostnet/host_lwt_unix.ml
- src/hostnet/host_uwt.ml
- src/hostnet/hostnet_dns.mli
- src/hostnet/slirp.ml
- src/hostnet/slirp.mli
- src/hostnet_test/slirp_stack.ml
- src/hostnet_test/suite.ml
When performing a `docker push` to `localhost`, `docker` will look up both `localhost` and `localhost.local`. Unfortunately the Mac will seriously attempt to look up `localhost.local` using mDNS which takes several seconds to timeout.
This patch special-cases `localhost.local`, making it always return a failure. This allows lookups of other .local names to continue working.
Related to docker/for-mac#1536
> DNS: don't attempt to look up localhost.local

- src/hostnet/host_lwt_unix.ml
- src/hostnet/host_uwt.ml
- src/hostnet_test/suite.ml
Currently a query for `foo.local` can use the host resolver and this may involve real mDNS, which can be very slow. At the moment our current client (linuxkit, previously known as Moby) has a domain name set to `local` which causes lots of lookups of `foo.local` names which don't exist, which each incur a ~5s timeout.
This patch returns `NXDomain` for all lookups of `*.local` for now.
> DNS: don't use mDNS at all

- repo/darwin/packages/local/slirp.local/opam
- src/bin/jbuild
- src/bin/main.ml
- src/hostnet/host_lwt_unix.ml
- src/hostnet/host_uwt.ml
- src/hostnet/jbuild
- src/hostnet/mux.ml
- src/hostnet/mux.mli
- src/hostnet/sig.ml
- src/hostnet/slirp.ml
- src/hostnet/stubs_utils.c
- src/hostnet/utils.ml
- src/hostnet/utils.mli
- Previously we would close `Uwt` connections asynchronously. Switch from `close` to `close_wait` to clean up as much stuff as possible between connections.
- In some error cases we printed to stdout. Switch to using the logging system.
- Catch and log any stray exceptions in the `listen` callbacks, just in case
- Discover and use `SOMAXCONN` rather than the hardcoded values `32` and `5`
- Re-add missing diagnostic data to the `.tar` and tidy up the file modes and times.
> Improve the error handling in port forwarding

- README.md
- docs/ethernet.md
- docs/ethernet.svg
- docs/mac.svg
- docs/ports.md
- docs/win.svg
- src/hostnet/stubs_utils.c
- add a Windows and Mac example plumbing diagram
- add `SOCK_STREAM` and `SOCK_DGRAM` to the main `vpnkit` diagram
- link to hyperkit and Mirage TCP/IP
- add a high-level walk-through describing what happens when a process in a Linux VM connected to `vpnkit` attempts to establish a TCP connection
> Update the documentation

- src/hostnet/stubs_utils.c
Problem spotted by yallop in
https://github.com/moby/vpnkit/commit/8d718125a66fbe746ba17ad3e85b7924ac0ed9a4#commitcomment-21930309
> Add `value` parameter to SOMAXCONN binding

- src/bin/main.ml
- src/hostnet/hostnet_dns.ml
- src/hostnet/hostnet_dns.mli
- src/hostnet/slirp.ml
- src/hostnet/slirp.mli
- src/hostnet_test/slirp_stack.ml
- src/hostnet_test/suite.ml
Previously the only way to access ports exposed on the Host from the VM was to know and hardcode the virtual IP `192.168.65.1` (although this can be changed via the database).
This patch adds a command-line argument `--host-names` which accepts a comma-separated list of DNS names which will be mapped to the current host virtual IP.
The default name is `vpnkit.host` but this can be overriden or extended.
> Add optional builtin DNS names

- opam
- repo/darwin/packages/local/slirp.local/opam
- src/bin/connect.ml
- src/bin/jbuild
- src/bin/main.ml
- src/hostnet/capture.ml
- src/hostnet/cstructs.ml
- src/hostnet/dhcp.ml
- src/hostnet/dhcp.mli
- src/hostnet/error.ml
- src/hostnet/filter.ml
- src/hostnet/forward.ml
- src/hostnet/host_lwt_unix.ml
- src/hostnet/host_uwt.ml
- src/hostnet/hostnet_dns.ml
- src/hostnet/hosts.ml
- src/hostnet/jbuild
- src/hostnet/mux.ml
- src/hostnet/slirp.ml
- src/hostnet/vmnet.ml
- src/hostnet_test/forwarding.ml
- src/hostnet_test/jbuild
- src/hostnet_test/main_lwt.ml
- src/hostnet_test/main_uwt.ml
- src/hostnet_test/slirp_stack.ml
- src/hostnet_test/suite.ml
- src/hostnet_test/test_nat.ml
- src/ofs/active_list.ml
- src/ofs/jbuild
Previously the `-w` and `-warn-error` compiler arguments were lost with the switch to `jbuilder`. This PR
- fixes all the warnings including
- the `Lwt_unix.bind` deprecation warning by using the new `Lwt_unix.Versioned.bind_2`
- avoiding pattern matching on a `Failure <string>`
- re-enables `-w` and selective `-warn-error`
> Fix warnings, selectively re-enable -warn-error

- src/bin/main.ml
- src/hostnet/host_lwt_unix.ml
- src/hostnet/host_uwt.ml
- src/hostnet/utils.ml
- src/hostnet/utils.mli
Previously we always used `SOMAXCONN` for the `listen(2)` backlog. This patch allows the backlog to be overriden.
> Add command-line argument `--listen-backlog <n>`

- src/hostnet/host_uwt.ml
These happen quite frequently and cause people to think they're suffering from an IPv6 problem, even though it's probably unrelated.
> Avoid logging spurious DNS AAAA lookup failures

- Makefile
- src/bin/bind.ml
- src/hostnet/host_uwt.ml
- src/hostnet/sig.ml
- src/hostnet/vmnet.ml
- src/hostnet_test/forwarding.ml
- src/hostnet_test/hosts_test.ml
- src/hostnet_test/main_lwt.ml
- src/hostnet_test/main_uwt.ml
- src/hostnet_test/suite.ml
- src/hostnet_test/test_http.ml
- src/hostnet_test/test_nat.ml
- remove unnecessary error logs (triggered by the tests)
- only test the `Uwt` backend since the `Lwt_unix` one is known broken
- run the tests with `List.iter` so we can associate the log output with the test that generated it
> Improve logging and make the tests easier to debug

- src/hostnet_test/suite.ml
We impose a connection limit to avoid hitting the system limits (particularly the global limits on Mac). Previously the test would check that we couldn't exceed the connection limit. This patch extends the test to check that, when the limit is raised, we can still make outgoing connections. This verifies that the act of hitting the limit does not break the stack i.e. we should be able to recover afterwards.
> test: check what happens after we hit the connection limit

- scripts/common.sh
- src/bin/bind.ml
- src/hostnet/host_lwt_unix.ml
- src/hostnet/host_uwt.ml
- src/hostnet/sig.ml
- src/hostnet_test/main_uwt.ml
- src/hostnet_test/suite.ml
This is a basic sanity check of the underlying I/O engine.
Note that Lwt_unix calls `select` which fails with `EINVAL` so we skip this test. This is part of the reason we switched the default to `Uwt`/`libuv` anyway.
> test: check that we can consume more than 1024 file descriptors

- README.md
- docs/transparent-http-proxy.md
The latest master build of Docker for Mac has the latest vpnkit which
includes the transparent proxy support. Since it's off by default,
this document describes how to turn it on and play with it.
> Describe how to play with the transparent HTTP proxy

- go/Makefile
linuxkit/virtsock currently needs cgo for the HVSOCK bindings. Pass
-static so we can run the code in a scratch container.
> proxy: make sure we build static binary

- circle.yml
The `brew install` step is failing because:
>  Error: libffi 3.0.13 is already installed
>  To upgrade to 3.2.1, run `brew upgrade libffi`
> Attempt to fix CircleCI

- src/hostnet/hostnet_http.ml
- src/hostnet/hostnet_http.mli
- src/hostnet_test/suite.ml
- src/hostnet_test/test_http.ml
This PR adds support for basic 'excludes' which are a list (comma or whitespace separated) of entries like:
- `foo.com`: any subdomain of `foo.com`
- `*.foo.com`: any subdomain of `foo.com`
- `foo.*.com`: any subdomain of `foo.(anything).com`
- `1.2.3.4/24`: any address on the IPv4 network
If the IP destination or the HTTP request header (NB the HTTPS header is not available) match any of these excludes then the request is forwarded directly to the destination without being bounced via the proxy.
> Respect the 'excludes' in the transparent http proxy

- src/hostnet_test/suite.ml
These queries are special-cased and should return immediately.
The previous timeout was 1s and would occasionally trigger on a
loaded CI machine. This patch makes the timeout 5s.
> test: expect DNS .local queries to take < 5s

- .travis.yml
- go/Dockerfile
- go/Dockerfile.build
- go/Dockerfile.scratch
- go/Makefile
Since travis has a very old Docker, this builds in 2 phases:
1. build the Go binaries in an alpine image
2. build the final FROM scratch image using COPY
This is based on the linuxkit rules in
https://github.com/linuxkit/linuxkit/blob/master/pkg/vpnkit-forwarder/Makefile
> travis: build a docker image with /vpnkit-{forwarder,expose-port}

- go/hooks/post_push
Docker Cloud autobuilds support hook scripts which can be used to push custom tags. The LinuxKit convention is to tag binary images with the git tree hash of the source code i.e. the hash of the contents and not the history (the commit). This means that if more commits happen but the contents don't change, the tag remains the same too.
> Add go/hooks/post_push to push an custom tag

- go/hooks/post_push
Previously the script failed to compute the tree SHA because the `git ls-tree` in the Docker Cloud environment didn't like the path `../go`. It works fine as `go` if we `cd ..` first.
> Fix the linux image post_push script

- .travis.yml
- go/Dockerfile.build
- go/Dockerfile.scratch
- go/Makefile
Try to upgrade Docker to 17.05 to see if we can use the multi-stage build instead of maintaining two sets of Dockerfiles.
> travis: update to docker 17.05 for multistage build

- go/Dockerfile
- go/Dockerfile.expose-port
- go/Makefile
- `Dockerfile`: builds `vpnkit-forwarder`
- `Dockerfile.expose-port`: builds `vpnkit-expose-port`
This will allow one to become a linuxkit service and the other to be part of system init.
> go: split into 2 images

- go/Dockerfile.expose-port
- go/Makefile
- go/cmd/vpnkit-iptables-wrapper/README.md
- go/cmd/vpnkit-iptables-wrapper/main.go
This wrapper calls vpnkit-expose-port when swarm service ports are
opened by dockerd using iptables.
To be used up by dockerd it has to be in path before the regular
iptables. The wrapper expects /sbin/iptables to contain the original
binary.
This is a go version of the iptables-wrapper originally written in
OCaml:
https://github.com/linuxkit/linuxkit/blob/f27c3ff5eda58d76e49ce5129b3cb29e402be272/alpine/base/pinata-iptables/main.ml
> add vpnkit-iptables-wrapper

- src/bin/main.ml
- src/hostnet/host_lwt_unix.ml
- src/hostnet/host_uwt.ml
- src/hostnet/slirp.ml
- src/hostnet_test/suite.ml
Previously we disabled queries for `*.local` to avoid using (slow) mDNS but some users do use this domain and need it to work.
This PR
- removes the workaround so `*.local` queries will work
- sets the default domain name to `localdomain` rather than `local` so we don't trigger mDNS by accident
Related to [docker/for-mac#1811]
> Don't disable DNS queries for .local

- src/bin/main.ml
- src/hostnet/slirp.ml
- src/hostnet/slirp.mli
- src/hostnet_test/slirp_stack.ml
When `bridge-connections` is enabled the server will reserve more IP addresses for clients such as LinuxKit which connect to the vpnkit network. Previously it was not possible to adjust fully the range of addresses handed out, so if you had a clash you were out of luck.
This patch plumbs through a new `slirp/highest-ip` setting so that clashes can be worked around.
Related to [docker/for-mac#1803]
> Dhcp: make the dynamic DHCP range configurable

- src/hostnet/slirp.ml
Previously the `highest_ip` was used everywhere except the logic which
allocates IP addresses to clients of the bridge.
> Use the configured highest_ip in the bridge

- go/cmd/vpnkit-expose-port/main.go
- go/pkg/vpnkit/connection.go
- go/pkg/vpnkit/doc.go
- go/pkg/vpnkit/port.go
This hides the details of the current port expose protocol so that we can more easily change the protocol later.
The command-line tool `cmd/vpnkit-expose-port` allows the library to be tested easily.
> go: add a library to manage exposed ports

- go/vendor.conf
- go/vendor/github.com/docker/go-p9p/LICENSE
- go/vendor/github.com/docker/go-p9p/README.md
- go/vendor/github.com/docker/go-p9p/channel.go
- go/vendor/github.com/docker/go-p9p/client.go
- go/vendor/github.com/docker/go-p9p/context.go
- go/vendor/github.com/docker/go-p9p/dispatcher.go
- go/vendor/github.com/docker/go-p9p/doc.go
- go/vendor/github.com/docker/go-p9p/encoding.go
- go/vendor/github.com/docker/go-p9p/errors.go
- go/vendor/github.com/docker/go-p9p/fcall.go
- go/vendor/github.com/docker/go-p9p/logging.go
- go/vendor/github.com/docker/go-p9p/messages.go
- go/vendor/github.com/docker/go-p9p/overflow.go
- go/vendor/github.com/docker/go-p9p/readdir.go
- go/vendor/github.com/docker/go-p9p/server.go
- go/vendor/github.com/docker/go-p9p/session.go
- go/vendor/github.com/docker/go-p9p/transport.go
- go/vendor/github.com/docker/go-p9p/types.go
- go/vendor/github.com/docker/go-p9p/version.go
- go/vendor/github.com/moby/datakit/LICENSE.md
- go/vendor/github.com/moby/datakit/README.md
- go/vendor/github.com/moby/datakit/api/go-datakit/README
- go/vendor/github.com/moby/datakit/api/go-datakit/client.go
- go/vendor/github.com/moby/datakit/api/go-datakit/config.go
- go/vendor/github.com/moby/datakit/api/go-datakit/doc.go
- go/vendor/github.com/moby/datakit/api/go-datakit/snapshot.go
- go/vendor/github.com/moby/datakit/api/go-datakit/transaction.go
- go/vendor/github.com/moby/datakit/api/go-datakit/watch.go
This should make the `vpnkit` package self-contained. Note none of the types from these libraries are visible in the interface.
> go: vendor docker/go-p9p and moby/datakit

- src/hostnet/slirp.ml
This reverts 732bdaa734db1f94f0e5e859974dfaa320ad5587 and may prevent https://github.com/djs55/miragetcpip/blob/f5b16043c57f71d5fdf1a7cf7ab7ccdde291cca1/tcp/user_buffer.ml#L164 from raiseing `Invalid_argument` exceptions
Related to #255
> Temporarily revert the MTU to 1500

- src/hostnet_test/suite.ml
- src/hostnet_test/test_half_close.ml
This patch adds 2 simple test cases, where a server is run on localhost and connected to via vpnkit via the Mirage TCP client. Both cases use a simple request / response protocol where the connection is half-closed after the request is written and before the response is written, to check that the response is still relayed correctly.
The `test_mirage_half_close` performs the half-close via the Mirage stack; the `test_host_half_close` performs the half-close via the Host stack.
> test: add cases for half-close

- src/bin/main.ml
- src/hostnet/slirp.ml
- src/hostnet/slirp.mli
- src/hostnet/vmnet.ml
- src/hostnet_test/slirp_stack.ml
The virtual bridge support in vpnkit has been enabled by default in Docker for Mac for several edge releases and 17.06 stable without any reported issues. This PR removes the old code that could still be enabled with a database key.
Changes:
- Remove non-bridge mode everywhere and move the vnet switch to the config, so we don't have to pass it around
- Rename l2_switch and other l2_* variables to vnet_* to make it clearer that they relate to the virtual network
- Fix tests to use a dynamic mac and run them on the new bridge (bridge mode was disabled for tests)
> Remove non-bridge mode

- src/hostnet/frame.ml
- src/hostnet/frame.mli
- src/hostnet/hostnet_icmp.ml
- src/hostnet/hostnet_icmp.mli
- src/hostnet/slirp.ml
- src/hostnet_test/slirp_stack.ml
- src/hostnet_test/suite.ml
- src/hostnet_test/test_half_close.ml
- src/hostnet_test/test_http.ml
- src/hostnet_test/test_nat.ml
- src/hostnet_test/test_ping.ml
This PR adds NAT-like support for ICMP echo requests and responses.
When requests arrive, they are forwarded via use-space sockets with distinct ids, and then the ids are used to route the responses back to the correct sender.
> Add support for ICMP echo request forwarding

- src/bin/main.ml
- src/hostnet/slirp.ml
- src/hostnet/slirp.mli
- src/hostnet_test/slirp_stack.ml
- src/ofs/active_config.ml
Previously we would timeout switch ports after 300s of inactivity. Ideally active connections would be configured to send keep-alive packets sooner than this. To better support cases with no keep-alives, it's useful to be able to reconfigure the idle timeout (e.g. to make it much bigger or disable it altogether).
This patch adds
- a command-line argument `--port-max-idle-time`
- a database key `slirp/port-max-idle-time`
which allow the default 300s to be overriden. Values `<= 0` disable the timeout mechanism completely.
Related to #235
Related to #234
> Allow switch port timeout to be configured

- src/hostnet/hostnet_dns.ml
- src/hostnet/hostnet_dns.mli
- src/hostnet/slirp.ml
Previously there was no way to locate the connections associated with
an endpoint to shut them down. This patch adds a map of TCP `id` to
`unit Lwt.u` and a function `Endpoint.destroy` which triggers the
disconnection of all the active connections.
Related to #260
> Add a Endpoint.destroy which closes active connections

- CHANGES.md
- Makefile
- pkg/pkg.ml
- vpnkit.descr
- vpnkit.opam
This PR adds the modern OCaml/opam boilerplate for handling releases i.e.
- a simple `topkg` configuration (set to automatic)
- a `make opam-pkg` target which will (hopefully) create a set of package metadata which is acceptable to the upstream opam-repository
Minor changes include
- fix URLs in the opam file to point to `moby` rather than `docker`
- remove an unnecessary dependency on `ocamlfind`
> Update CHANGES for a v0.1.0 release

- CHANGES.md
- Makefile
- src/bin/depends.ml.in
- src/bin/jbuild
- src/bin/main.ml
- vpnkit.opam
Previously the opam file invoked `make` which performed some watermarking and then invoked `jbuilder`. This PR simplifies the build by using `jbuilder subst` for watermarking and having the `opam` file directly invoke `jbuilder`.
> Simplify the opam build

- go/cmd/vpnkit-list-ports/.gitignore
- go/cmd/vpnkit-list-ports/main.go
- go/pkg/vpnkit/port.go
The function `ListExposed` returns the list of current port forwards.
The function `Unexpose` allows a listed port forward to be unexposed
by internally opening and then closing the `ctl` file-- the protocol
unexposes the port on `clunk`.
> go: add ability to list exposed ports and unexpose

- go/pkg/vpnkit/port.go
Rather than expose the fields of the Port structure directly
which might tempt people to replace them, we keep them private but
return accessor functions. These allow people to discover (for example)
the external port of a forward.
> go: add accessor functions to Port

- CHANGES.md
- src/hostnet/capture.ml
- src/hostnet/filter.ml
- src/hostnet/sig.ml
- src/hostnet/slirp.ml
- src/hostnet/vmnet.ml
- src/hostnet/vmnet.mli
- src/hostnet_test/slirp_stack.ml
- src/hostnet_test/suite.ml
- src/hostnet_test/test_bridge.ml
This updates the protocol from v1 to v22. The new features are:
- New Preferred_ipv4 command may be used to request a specific IP which will be assigned to the UUID. The UUID can then be reused to get the same IP in the future. This replaces the old mechanism that encoded the requested IP in the UUID itself.
- New Response message returned for Ethernet and Preferred_ipv4 commands. The Response message either contains a Vif structure on success or a Disconnect with a reason message on failure. This allows errors to be reported back to the client, such as when the preferred IP address is already in use.
This PR also adds test for the bridge and the Preferred_ipv4 command. See individual commits for more details.
These changes are not backwards compatible. Other libraries that use VPNKit …
> Protocol update: Add support for error messages, preferred IPv4 addresses

- src/hostnet/host.ml
We wish to detect when connections have disappeared (e.g. when the
host network environment changes) and free any associated filehandles.
> Enable TCP keep-alives on external connections

- src/hostnet/host.ml
- src/hostnet/slirp.ml
Disable Nagle on both the external connections (via `Uwt.Tcp.nodelay`)
and on the internal connections (by using `write_nodelay` instead of
`write`)
> Disable Nagle's algorithm

- src/hostnet/host.ml
- in `read`: emulate a connected socket by dropping all incoming traffic that doesn't strictly match the address we have `connect`ed to
- in `recvfrom`: drop packets with an invalid from address but don't fail the thread
Note that the UDP NAT implementation uses `recvfrom` (not `read`). Previously the failed `recvfrom` would cause the NAT rule to be shutdown. It's not clear whether this missing `sockaddr` condition can be triggered easily, but it's suspicious that `libuv` permits a `NULL` which gets translated into a `None` by `uwt`.
> Improve UDP receive

- src/hostnet_test/slirp_stack.ml
- src/hostnet_test/suite.ml
- src/hostnet_test/test_bridge.ml
- src/hostnet_test/test_half_close.ml
- src/hostnet_test/test_http.ml
- src/hostnet_test/test_nat.ml
- src/hostnet_test/test_ping.ml
This makes debugging test failures a lot easier.
> test: record .pcap traces, one per test

- c/vpnkit-9pmount-vsock/hooks/post_push
- c/vpnkit-tap-vsockd/hooks/post_push
These hooks will cause the Docker Cloud autobuilder to tag the images
using the LinuxKit content hash convention.
> Add post_push hooks for vpnkit-{tap-vsockd,9pmount-vsock}

- go/cmd/vpnkit-register-uuid/.gitignore
- go/cmd/vpnkit-register-uuid/README.md
- go/cmd/vpnkit-register-uuid/main.go
- go/pkg/vpnkit/vmnet.go
- go/vendor.conf
This will allow us to connect, allocate UUIDs and query the IP mapping.
The API is demonstrated using an example command `vpnkit-register-uuid`
Note we query the IP mapping via issuing a DHCP request, like a real client would.
Fixes #257 -- to forward from host to guest without an agent:
1. generate a UUID for the VIF (cache this somewhere if you want the IP to persist)
2. use the new vmnet API to connect a VIF and query the IP
3. use the UUID when starting hyperkit
4. use the port forwarding API to forward to the guest IP
> go: add a client for the Vmnet protocol

- go/cmd/vpnkit-register-uuid/main.go
- go/pkg/vpnkit/vmnet.go
This allows Go programs to check that a UUID <-> IP mapping exists and to create one (provided the UUID and IP are free)
> go: add binding for Preferred_ipv4

- repo/darwin/packages/dev/hvsock.1.0.1/descr
- repo/darwin/packages/dev/hvsock.1.0.1/opam
- repo/darwin/packages/dev/hvsock.1.0.1/url
- repo/darwin/packages/dev/protocol-9p.0.11.3/descr
- repo/darwin/packages/dev/protocol-9p.0.11.3/opam
- repo/darwin/packages/dev/protocol-9p.0.11.3/url
- repo/win32/packages/dev/hvsock.1.0.1
- repo/win32/packages/dev/protocol-9p.0.11.3
- src/bin/jbuild
- src/hostnet/jbuild
- src/hostnet_test/jbuild
- src/ofs/jbuild
- vpnkit.opam
Previously strange things happened when we linked both `uwt` and `lwt.unix`, `lwt.preemptive` at the same time. Obviously the `lwt.unix` functions won't work if used, but I suspect there may be module-level initialisation that conflicts (or could conflict) with `uwt`. Some extra linkage happened during the recent backend refactor *and* the versions of `uwt` and `lwt` were both upgraded.
Related to #286 but this is a good change anyway.
> Remove unnecessary Unix linkage

- c/vpnkit-9pmount-vsock/Dockerfile
- c/vpnkit-9pmount-vsock/Makefile
The container was built from scratch, but vpnkit-9pmount-vsock calls
/bin/mount to set up the mount point after opening the fd.
Also allow networking in container build.
> Add /bin/mount to vpnkit-9pmount-vsock container

- src/hostnet/frame.ml
- src/hostnet/frame.mli
- src/hostnet/host.ml
- src/hostnet/hostnet_icmp.ml
- src/hostnet/hostnet_icmp.mli
- src/hostnet/hostnet_udp.ml
- src/hostnet/hostnet_udp.mli
- src/hostnet/sig.ml
- src/hostnet/slirp.ml
- src/hostnet/stubs_utils.c
- src/hostnet/utils.ml
- src/hostnet/utils.mli
This PR fixes ICMP and UDP traceroute (on Mac) by:
- setting the TTL on outgoing ICMP and UDP
- forwarding ICMP Destination unreachable and TTL exceeded messages
On windows we don't receive the ICMP messages for an unknown reason.
Fixes #193 
Fixes #194
> Fix ICMP and UDP traceroute

- go/pkg/vpnkit/port.go
- go/pkg/vpnkit/port_test.go
Using int16 caused large ports to be negative.
For example, the original port was 44134.
```
$ ./vpnkit-list-ports
2017/11/07 11:26:02 Dialling unix /Users/guillaumerose/Library/Containers/com.docker.docker/Data/s51
tcp forward from 0.0.0.0:-21402 to 10.111.24.47:-21402
```
> go: use uint16 for ports

- go/cmd/vpnkit-forwarder/one.go
- go/pkg/libproxy/expose_port.go
- go/pkg/libproxy/proxy.go
Signed-off-by: Ilya Dmitrichenko <errordeveloper@gmail.com>
> proxy: move helper methods from go/cmd/vpnkit-forwarder to go/pkg/libproxy

- src/bin/logging.ml
- src/bin/main.ml
- src/hostnet/configuration.ml
- src/hostnet/dhcp.ml
- src/hostnet/dhcp.mli
- src/hostnet/host.ml
- src/hostnet/hostnet_dns.ml
- src/hostnet/hosts.ml
- src/hostnet/slirp.ml
- src/hostnet/slirp.mli
- src/hostnet/stubs_utils.c
- src/hostnet_test/slirp_stack.ml
Previously everything could be configured via the database but only some options could be configured via the command-line. This PR completes the command-line support.
In particular:
- `--dns <filename>` names a file which will be watched for changes. It is re-read on change and used to dynamically reconfigure the upstream DNS servers
- `--http <filename>` names a file which will be watched for changes. It is re-read on change and used to dynamically reconfigure transparent HTTP redirection.
- `--log-destination <destination>` allows the logging to be configured
The PR also improves the logging by
- defaulting to writing to the terminal (see `--log-destination`) rather than failing silently
- printing an error message if `--ethernet` is not provided
> Improve support for configuration via the command-line

- src/bin/main.ml
- src/hostnet/configuration.ml
- src/hostnet/dhcp.ml
- src/hostnet/slirp.ml
Previously it was possible to configure the `--gateway-ip` and the
(DHCP) `--highest-ip` but not the `--lowest-ip`. This patch completes
the IP address command-line arguments.
Note the configuration binding `peer` is renamed to `lowest_ip` for symmetry
with `highest_ip`
> Add command-line `--lowest-ip`

- src/bin/main.ml
Previously we failed to add the `--lowest-ip` argument and we used
`--highest-dhcp-ip` rather than `--highest-ip`.
> Use `--lowest-ip` and `--highest-ip` for the commandline

- src/bin/main.ml
- src/hostnet/configuration.ml
- src/hostnet/hostnet_dhcp.ml
- src/hostnet/hostnet_dhcp.mli
- src/hostnet/slirp.ml
- src/hostnet_test/slirp_stack.ml
This PR adds the command-line option `--dhcp-path <filename>` which names a json-formatted configuration file containing some of the DHCP settings. Eventually it should contain them all, but for now it has:
```
{"searchDomains":[],"domainName":"cam.docker.com"}
```
The domain name is taken from the command-line `--domain` if present, otherwise it uses this file, failing that it uses `localdomain` as a default. The `--domain` command-line is now deprecated and will be removed.
The search domains are taken from this new file if present, otherwise it uses information in the `--dns` configuration file.
> Support a DHCP configuration file

- .travis.yml
The most recent released docker-ce is 17.11, we need at least 17.05
but this version is now gone from the upstream repo.
> travis: remove docker-ce version pin

- src/hostnet/hostnet_http.ml
- src/hostnet/hostnet_http.mli
- src/hostnet/slirp.ml
- src/hostnet_test/test_http.ml
Previously we only supported a transparent HTTP proxy, where an HTTP client sends a request as normal but this is intercepted by `vpnkit` at the TCP-level, rewritten and redirected to the upstream proxy. One disadvantage of this approach is that DNS resolution is first performed by the client before the TCP connection is created. Some environments do not have working DNS on end user devices -- instead, they restrict DNS resolution to the proxy only. In transparent mode this fails because the TCP connection is never created.
This PR adds regular, non-transparent HTTP proxy support which works irrespective of whether an upstream proxy is defined:
- if there is an upstream proxy defined, then we proxy requests at the TCP level to it
- if there is no upstream proxy, then we rewrite the …
> Add more HTTP proxy modes

- src/bin/main.ml
- src/hostnet/host.ml
We use the Mac `DNSServiceRef` API to resolve queries. Previously we used the blocking interface and ran in a worker thread pool with `Uwt_preemptive.detach`. This is unfortunate because
- DNS queries take up to 30s to time out, therefore lots of them can be in the waiting-to-fail state
- the maximum size of the thread pool is 4
This PR
- uses the lower-level `DNSServiceRef` API where we can access a file descriptor and use `Uwt.Poll` to wait for it to become `Readable`. We now only need to use `Uwt_preemptive.detach` when actually reading the result, which should be fast.
- increases the size of the thread pool on Unix systems to 1024.
Unfortunately to use the low-level interface we have to recursively resolve CNAMEs ourselves. This code contains a copy of the function from the low-level …
> Mac: make the DNS more scalable

- Makefile
- scripts/common.sh
- src/bin/main.ml
- src/hostnet/configuration.ml
- src/hostnet/hostnet_dhcp.ml
- src/hostnet/hostnet_dns.ml
- src/hostnet/hostnet_dns.mli
- src/hostnet/slirp.ml
- src/hostnet/slirp.mli
- src/hostnet_test/slirp_stack.ml
- src/hostnet_test/suite.ml
Previously we had a single "gateway" IP which
- passes through to `localhost` on the host
- also does NTP
- also does DNS
- and now also does HTTP proxies
As we add more services, the ports for those will mask the ports available for connecting to `localhost`. For example it is not possible to access port 3128 on the host any more, as it is masked by the new HTTP proxy.
This PR separates the local host passthrough from the internal services. The internal services are kept on the gateway ip via `--gateway-ip` and named by `--gateway-names`. The local host passthrough is now on `--host-ip` and named by `--host-names`.
This PR also removes the unused "extra DNS IPs" and simplifies the "make test" target.
> Separate the localhost proxy from internal services

- repo/darwin/packages/dev/tcpip.dev/url
- scripts/common.sh
This is a subset of #314 which allows the system compiler to be used, rather than a compiler built through `opam`. In theory this includes the 4.06.0 compiler, although building this in CI will require an update to the package repository.
> Allow the system compiler to be used

- repo/darwin/packages/upstream/menhir.20171013/url
- repo/win32/packages/upstream/menhir.20171013/url
- src/hostnet/hostnet_http.ml
- backport #325 
- add a mirror of the `menhir` package as the primary website is down
> Backport the HTTP HEAD fix onto the stable branch

- src/hostnet/hostnet_http.ml
- close connections after `HTTP CONNECT` is finished
- avoid adding a duplicate `host` header
> Backport HTTP proxy fixes

- src/hostnet/hostnet_http.ml
- improve the connection handling in the HTTP proxy
- avoid creating a duplicate `host` header in the HTTP request
> HTTP proxy fixes

- go/pkg/vpnkit/connection.go
In Docker4Windows, we need to create connections using hvsock datakit client instead of linux sockets. 
PR add a new `vpnkit.Connection` constructor function allowing to create connections for arbitrary datakit.Client
> Allow to create connections for arbitrary clients

- src/hostnet/hostnet_http.ml
RFC2616[1] says that if the port number is not 80 (the default) then
the port must be included in the `Host` header.
[1] https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23
Related to https://github.com/docker/for-mac/issues/2392
> [stable] HTTP proxy: include the port number in the host header

- src/hostnet/hostnet_http.ml
Since the system can have different proxies for HTTP and HTTPS, we
should separate the traffic by using two different ports. We can then
use the HTTP proxy setting for the HTTP traffic and the HTTPS proxy
setting for the HTTPS traffic.
> [stable] HTTP proxy: use 3128 for HTTP and 3129 for HTTPS

- src/hostnet/hostnet_http.ml
- src/hostnet_test/test_http.ml
Previously we would omit the port from the host header which is ambiguous. RFC2616 says that the port number has to be included.
> HTTP proxy: include the port number in the host header

- src/hostnet/hostnet_http.ml
Since the system can have different proxies for HTTP and HTTPS, we
should separate the traffic by using two different ports. We can then
use the HTTP proxy setting for the HTTP traffic and the HTTPS proxy
setting for the HTTPS traffic.
> HTTP proxy: use 3128 for HTTP and 3129 for HTTPS

- src/hostnet/hostnet_http.ml
- src/hostnet/hostnet_http.mli
- src/hostnet_test/test_http.ml
Previously we would proxy at the TCP/byte level if there was an upstream proxy defined. Unfortunately this omits to send the `Proxy-Authorization` header and so doesn't work. After this PR all requests -- whether explicitly sent to the proxy or transparently proxied -- are parsed and routed, with necessary authentication headers added.
The configuration interface has had to change too: previously a proxy was an `<IP:port>` but now we also need an optional username and password, so the API takes a URI of the form `http://user:pass@host:port`
One benefit of losing the special cases is that there is a single request-handling codepath. The differences are handled by the function `route` which decides where to send the request i.e. to an upstream proxy or to the origin server. A transparently …
> Fix HTTP proxy authentication

- src/hostnet/hostnet_http.ml
- src/hostnet/hostnet_http.mli
- src/hostnet_test/test_http.ml
Previously we could say `10.0.0.0/16` but not `10.0.0.1`. This patch accepts IP addresses as well as prefixes and subdomains.
Previously the caller of `Excludes.matches` had to take a string which could be a hostname or IP, attempt to convert it to an IP and then call `Excludes.matches ~ip ~host`. This PR simplifies the `Excludes.matches` interface to `string -> t -> bool`, so the caller doesn't have to know that the excludes matches are done both on the basis of IP address ranges and subdomains.
> http: allow excludes to contain IPs as well as IP prefixes

- src/hostnet/hostnet_dns.ml
- src/hostnet/hostnet_http.ml
- src/hostnet/hostnet_http.mli
- src/hostnet_test/test_http.ml
#330 test: check that the HTTP proxy doesn't duplicate host: headers
#332 test: check the HTTP proxy handles HEAD requests
#334 test: strengthen the HTTP proxy host header test
#341 Fix HTTP proxy authentication
#343 allow excludes to contain IPs as well as IP prefixes
#344 dns: return NXDomain for a builtin where we don't have RRs
> [stable 17.12.x] Backport HTTP proxy fixes

- src/hostnet/hostnet_http.ml
- src/hostnet/hostnet_http.mli
- src/hostnet/slirp.ml
- src/hostnet_test/test_http.ml
HTTP traffic on port 80 or 443 are dispatched based on destination IP address:
- if to "localhost" (e.g. `docker.for.mac.localhost`) they are forwarded to 127.0.0.1
- if to anywhere else they are funnelled through the transparent proxy
HTTP traffic sent to vpnkit's gateway IP on port 3128 (the HTTP proxy) but whose final destination is one of the names for the host's localhost is unfortunately routed to the wrong place.
This patch adds a `localhost_names` argument to the HTTP proxy `route` function. If the destination host is one of the `localhost_names` then it is rewritten as `localhost` which will then cause connections to the host's `localhost` as expected.
> HTTP proxy: fix localhost

- go/cmd/vpnkit-expose-port/main.go
- src/bin/main.ml
- src/hostnet/forward.ml
- src/hostnet/forward.mli
- src/hostnet_test/forwarding.ml
- src/ofs/active_list.ml
Previously we would instantiate the `Active_list` functor once per `--port` argument which was wrong because the table of active connections is in the resulting module-- we would end up with separate tables rather than a single shared table.
This PR creates one `Active_list` instance per-process and one 9P server per `--port` argument.
Tis PR also includes a fix to the `vpnkit-expose-port` example program.
> Fix for multiple `--port` arguments

- src/bin/main.ml
- src/hostnet/forward.ml
- src/hostnet/forward.mli
- src/hostnet/hostnet_http.ml
- src/hostnet/hostnet_http.mli
- src/hostnet/slirp.ml
- src/hostnet_test/forwarding.ml
- src/hostnet_test/test_http.ml
- src/ofs/active_list.ml
- [moby/vpnkit#346]: fix multiple --port arguments
- [moby/vpnkit#347]: fix proxy for docker.for.mac.http.internal
> [stable] more HTTP proxy fixes

- src/hostnet/hostnet_http.ml
- src/hostnet/hostnet_http.mli
- src/hostnet/slirp.ml
- src/hostnet_test/slirp_stack.ml
- src/hostnet_test/test_http.ml
We already support connections to the "host" name (e.g. `docker.for.mac.http.internal`). This patch adds support for the "host" IP too.
> http: handle connections to the "host" IP

- src/bin/main.ml
Previously it was 300s but it got accidentally typo'd to 30s when
we added the extra command-line arguments.
Related to [docker/for-win#1596]
> The default port max idle time should be 300s

- Makefile
A really stupid contribution.  I noticed that hyperkit does not generate its COMMIT and I meant to copy paste from here.
> Makefile: clean up generation of COMMIT and OSS-LICENSES

- appveyor.yml
- circle.yml
The cache will be invalidated if the repo/win32 directory containing
the package definitions is modified.
> appveyor: attempt to cache the _build/opam directory

- go/cmd/vpnkit-expose-port/main.go
- go/cmd/vpnkit-list-ports/main.go
- go/pkg/vpnkit/connection_darwin.go
- go/pkg/vpnkit/connection_windows.go
Darwin and Windows use a different control socket path, so adopt the
convention that if the user doesn't specifiy a path override, we use
the system one.
> go: set the default control socket path depending on OS

- src/bin/main.ml
- src/hostnet/configuration.ml
- src/hostnet/slirp.ml
We already have DNS names for the gateway and for the host. This
adds the command-line option `--vm-names` which is a comma-separated
list of DNS names which will be mapped to the VM's IP.
Note this only behaves properly in the common case of 1 VM. All VMs
will map the `--vm-names` to the first VM IP.
> dns: add names for the VM's IP

- Makefile
- circle.yml
- src/.gitignore
- src/bin/jbuild
- src/bin/main.ml
- src/bin/version.ml.in
In Docker for Mac we get logs that try to display the version of vpnkit, but don't.
I usually use the output of `git describe` instead of the raw sha, it is much more convenient, but it seems that the tags are somewhat different and don't allow that, I don't know why.  `git describe --tags` does though.
> Display the sha1 instead of %%VERSION%%

- appveyor.yml
- src/hostnet/hostnet_http.ml
- src/hostnet/hostnet_http.mli
- src/hostnet/slirp.ml
If the HTTP/HTTPS proxy is set to one of the special names for "localhost" (e.g. `docker.for.mac.localhost` on Docker for Mac) then we should connect to `127.0.0.1` in the transparent proxy. Previously we would do a DNS lookup for `docker.for.mac.localhost` which would obviously fail.
This restores the missing symmetry where all 4 combinations of HTTP,HTTPS and transparent,non-transparent inspect the `localhost_names` and `localhost_ips`. It would probably be better to refactor the DNS code to map these names in one central location but this requires a larger refactor.
> Handle HTTP proxy on the host's "localhost"

- src/hostnet_test/slirp_stack.ml
- src/hostnet_test/test_http.ml
- check that an HTTP GET works with all names for `localhost`
- check that the HTTP and HTTPS transparent proxy works with all names for `localhost`
Fixes #363
Tests #362
> Add more tests for localhost DNS names

- src/hostnet/hostnet_dns.ml
This isn't particularly interesting information, and triggers a lot
of log spam: see [docker/for-mac#2699]
> dns: avoid logging when we discover a name in /etc/hosts

- src/hostnet/vmnet.ml
Previously if the peer closes the ethernet socket (e.g. a hyperkit process
shuts down) then there would be a read error on the socket and we would log
> read EOF so closing connection
but we wouldn't close the connection (unlike in the "unexpected" error case).
This patch calls the idempotent function `disconnect` which wakes up callers
blocked in `after_disconnect` which includes the caller which will close
the underlying connection.
> Avoid leaking fd on ethernet socket close

- src/hostnet/hostnet_http.ml
- catch stray exceptions in the byte proxy and treat as EOF
- log any stray exceptions that hit the top-level handlers
> Improve the HTTP error handling

- src/hostnet/hostnet_icmp.ml
The ICMP sockets on the host are unusual in that they receive all the traffic seen by the host. For example if the user opens another terminal and runs `ping`, then `vpnkit` will see the responses too even though it didn't send the requests.
It's safe to ignore ICMP packets that we don't recognise since they weren't meant for us. This patch reduces the log level from `error` to `debug`.
Fixes #381
> ICMP: don't log an error if we can't parse an ICMP packet

- src/bin/bind.ml
Needed for https://github.com/docker/pinata/pull/9424, which renames `/var/tmp/com.docker.vmnetd.socket` as `/var/run/com.docker.vmnetd.sock`.
> Mac: adjust to vmnetd.sock being in /var/run

- go/pkg/vpnkit/connection_darwin.go
While at it also 'gofmt' the file.
Signed-off-by: Rolf Neugebauer <rolf.neugebauer@gmail.com>
> go: Import 'os' to fix a compile error

- src/hostnet/slirp.ml
These should be at `debug` rather than `info`.
> Downgrade 2 log lines per TCP connection

- src/bin/main.ml
The name `DEBUG` is too generic and could be triggered by accident.
> Rename environment variable DEBUG to VPNKIT_DEBUG

- c/vpnkit-tap-vsockd/Dockerfile
- c/vpnkit-tap-vsockd/log.c
- c/vpnkit-tap-vsockd/log.h
- c/vpnkit-tap-vsockd/protocol.c
- c/vpnkit-tap-vsockd/tap-vsockd.c
Previously we used a mixture of `DEBUG` `INFO` macros and calls to `syslog`. We had a `verbose` flag in the code but this wasn't hooked up to the command-line. This PR makes the code use logging macros everywhere and hooks up the `verbose` flag, removing `syslog` because there is no `syslog` in LinuxKit VMs.
Since a user of this will want to configure the interface once it has been brought up, this PR also adds a command-line `--post-up-script` which will be called as soon as the interface is created. The script can be used to run DHCP or otherwise configure the IP address of the interface. To make use of this easier, the final image has been upgraded to an `alpine` with the usual scripting tools.
> vpnkit-tap-vsockd: update logging, add a post-up script

- c/vpnkit-9pmount-vsock/9pmount-vsock.c
- c/vpnkit-9pmount-vsock/Dockerfile
- c/vpnkit-9pmount-vsock/log.c
- c/vpnkit-9pmount-vsock/log.h
- c/vpnkit-tap-vsockd/Dockerfile
- c/vpnkit-tap-vsockd/Makefile
- c/vpnkit-tap-vsockd/log.h
- c/vpnkit-tap-vsockd/tap-vsockd.c
The `AF_HVSOCK` patches were never merged in upstream Linux, instead Hyper-V support was added to `AF_VSOCK` instead. One consequence is the `AF_VSOCK` "port" is mapped into a special space of Hyper-V service GUIDs. This patch modifies `vpnkit-tap-vsockd` and `vpnkit-9pmount-vsock` to first try `AF_VSOCK` and then fall back to `AF_HVSOCK`.
This patch changes the command-lines from
```
--serviceid <guid>
```
to
```
--vsock <port>
```
> vpnkit-tap-vsockd, vpnkit-9pmount-vsock: try AF_VSOCK first, fall back to AF_HVSOCK

- src/bin/main.ml
In the `hvsock-listen://` codepath, we forgot to call `bind` which would cause the `listen` to return with `EINVAL` (reasonably) and then `vpnkit` to spin hard (unreasonably). So
- call `bind` before `listen`
- on error, wait 1s rather than spin hard
> hvsock: call `bind` before `listen`

- c/vpnkit-9pmount-vsock/9pmount-vsock.c
- c/vpnkit-tap-vsockd/tap-vsockd.c
These `struct sockaddr` values are on the stack and are therefore not pre-zeroed. Some of the Linux syscalls check for zeros (in particular `connect`) and will reject the calls with EINVAL if non-zero data is present.
> vpnkit-{9pmount,tap}-vsock: bzero struct sockaddr

- src/hostnet/capture.ml
- src/hostnet/filter.ml
- src/hostnet/sig.ml
- src/hostnet/vmnet.ml
- src/hostnet/vmnet.mli
- src/hostnet_test/packets.ml
- src/hostnet_test/slirp_stack.ml
- src/hostnet_test/suite.ml
- src/hostnet_test/test_nmap.ml
- src/hostnet_test/test_ping.ml
This new test case tries to connect to every port on the Host's localhost very quickly. Before we switched to `libuv` via `uwt` this kind of traffic could cause the process to exit.
This PR also fixes a long-standing bug in the harness which would cause the main ethernet listener thread to be cancelled after 4s, due to a timeout in the DHCP client.
> Add an "nmap" test case

- go/pkg/vmnet/vmnet.go
This allows library users to import vmnet without datakit.
Signed-off-by: Tibor Vass <tibor@docker.com>
> vmnet: move vmnet to its own package

- repo/darwin/packages/dev/hvsock.2.0.0/url
- src/bin/main.ml
In the future we will probably only support the URIs supported natively by the `hvsock` library, but in the meantime this PR adds support for `hvsock` URIs while keeping the existing `hvsock-listen` `hvsock-connect` and `fd:` URIs for backwards-compatibility.
> Add support for more hypervisor socket URIs

- go/cmd/vpnkit-forwarder/hvsock.go
- go/cmd/vpnkit-forwarder/main.go
Since AF_HVSOCK only exists in patched kernels, this changes the command-line to only require an AF_VSOCK port number. At runtime we detect whether the kernel is patched and use the correct
interface.
> vpnkit-forwarder: autodetect AF_VSOCK versus AF_HVSOCK

- go/cmd/dial-example/.gitignore
- go/cmd/dial-example/main.go
- go/pkg/libproxy/loopbackconn.go
- go/pkg/libproxy/multiplexed.go
- go/pkg/libproxy/multiplexed_test.go
- go/pkg/libproxy/stream_proxy.go
- go/pkg/vpnkit/dialer.go
- go/pkg/vpnkit/dialer_darwin.go
- go/pkg/vpnkit/dialer_linux.go
- go/pkg/vpnkit/dialer_windows.go
Previously we supported `io.Reader`, `io.Writer`, `io.Closer`, `ReadClose()` and `WriteClose()`. However it's useful to conform to the whole `net.Conn` interface since some libraries require it, notably the http client, the docker client and `net.Dialer`.
This bulk of this patch adds read and write deadlines. The local and remote address functionality is stubbed as it's not particularly meaningful.
> go: multiplexer: support net.Conn

- src/hostnet/hostnet_udp.ml
- src/hostnet/hostnet_udp.mli
- src/hostnet/slirp.ml
- src/hostnet/slirp.mli
- src/hostnet_test/test_nat.ml
There is a configurable global connection limit which is useful on platforms (such as macOS) which have abnormally low maximum file descriptor limits.
The UDP NAT binds a socket per internal source address, and expires it after it has been idle for 60s.
Unfortunately a UDP protocol which sends UDP from random source ports and which doesn't expect replies (such as that in `envoy`, as used by `kubeflow`) can quickly exhaust the global limit which then breaks other things, such as port forwards.
This PR adds a new limit on the total number of active UDP NAT table entries and sockets, and expires the oldest when the new limit is hit. This should keep the network usable even when using one of these chatty UDP protocols.
> Prevent UDP NAT overload from exhausting all available connections

- go/pkg/libproxy/loopbackconn.go
- go/pkg/libproxy/multiplexed.go
- go/pkg/libproxy/multiplexed_test.go
Previously it was possible for a concurrent `Write` and `Close` (or `CloseWrite`) to permute, triggering a fatal error in the remote's state machine.
This PR fixes the race condition by setting the local state before sending the `Close` or `CloseWrite` messages, which `Write` already checks for. This will prevent any further payloads being sent.
The test case tests this condition reliably by simulating a high-latency link, so it is easy to call `Write` while a `Close` is still being transmitted.
> pkg/libproxy: fix write-after-close race in the multiplexer

- go/pkg/libproxy/multiplexed.go
- go/pkg/libproxy/multiplexed_test.go
Previously it was possible for the client to confuse the server by sending
- `Close` then `Close`
- `Shutdown` then `Shutdown`
- `Close` then `Shutdown`
This PR suppresses these duplicate messages on the client-side. If the application calls `Close` then the second is a no-op.
> pkg/libproxy: fix double Close, Shutdown

- go/cmd/vpnkit-expose-port/main.go
- go/cmd/vpnkit-list-ports/main.go
- go/pkg/vpnkit/connection.go
- go/pkg/vpnkit/connection_unix.go
- go/pkg/vpnkit/port.go
We now have a `vpnkit.Client`:
```
// Client exposes and unexposes ports on vpnkit.
type Client interface {
Expose(context.Context, *Port) error
Unexpose(context.Context, *Port) error
ListExposed(context.Context) ([]*Port, error)
}
```
which we can use instead of the ad-hoc functions spread over both
the package (`vpnkit.ListExposed`) and Ports (`port.Expose`)
This should make this library easier to Mock for testing.
> Go: pkg/vpnkit: simplify the port interface

- go/cmd/vpnkit-expose-port/main.go
Previously we failed to set the protocol, so it was left as "unknown"
> vpnkit-expose-port: add the protocol to the Port

- .circleci/config.yml
- src/bin/main.ml
- src/hostnet/configuration.ml
- src/hostnet/slirp.ml
- src/hostnet_test/forwarding.ml
- src/hostnet_test/slirp_stack.ml
Clients can connect to services on the host as well as virtual services running on the "gateway" address. This PR allows extra virtual TCP services on the gateway to be configured which are automatically proxied to somewhere else. This is convenient if we can't use localhost because the ports are privileged and we can't easily bind there (for example DNS on port 53).
For example the argument `--tcpv4-forwards 53:8.8.8.8:53` sets up a virtual listener on `docker.for.mac.gateway.internal:53` and proxies all traffic to `8.8.8.8:53`.
> Add a notion of forwarded TCP services

- go/pkg/vpnkit/config.go
- go/pkg/vpnkit/config_test.go
- go/vendor.conf
- go/vendor/github.com/pkg/errors/LICENSE
- go/vendor/github.com/pkg/errors/README.md
- go/vendor/github.com/pkg/errors/errors.go
- go/vendor/github.com/pkg/errors/stack.go
- src/bin/main.ml
- src/hostnet/configuration.ml
- src/hostnet/gateway_forwards.ml
- src/hostnet/gateway_forwards.mli
- src/hostnet/slirp.ml
- src/hostnet_test/slirp_stack.ml
Previously we only supported a static set of forwards set via the command-line.
This PR adds support for a dynamic json config file, which is watched and reparsed when it changes.
Both the command-line and the dynamic json file may be used together, with the command-line rules taking precedence if there is a clash.
> Make UDP/TCP port forwards from the gateway dynamic

- src/bin/main.ml
Previously `vpnkit` would fail to start if the gateway forwards file didn't exist but the `--gateway-forwards` argument was provided. This makes it difficult to have the configuration written entirely dynamically, for example by another process starting in parallel.
With this patch `vpnkit` will log a warning but will read the file when it is created.
> Permit missing --gateway-forwards <file>

- go/Gopkg.lock
- go/Gopkg.toml
- go/pkg/vpnkit/dialer_windows.go
- go/vendor/github.com/linuxkit/virtsock/AUTHORS
- go/vendor/github.com/linuxkit/virtsock/LICENSE
- go/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock_fallback.go
- go/vendor/github.com/linuxkit/virtsock/pkg/hvsock/zsyscall_windows.go
- go/vendor/github.com/linuxkit/virtsock/pkg/vsock/fallback.go
- go/vendor/github.com/linuxkit/virtsock/pkg/vsock/hyperkit_darwin.go
- go/vendor/github.com/linuxkit/virtsock/pkg/vsock/vsock.go
- go/vendor/github.com/linuxkit/virtsock/pkg/vsock/vsock_linux.go
- go/vendor/github.com/linuxkit/virtsock/scripts/generate-authors.sh
I can now compile all tests on Mac but I have one last failing unit test:
```
=== RUN   TestUDPWriteError
--- FAIL: TestUDPWriteError (0.00s)
network_proxy_test.go:237: write udp 127.0.0.1:64614->127.0.0.1:25587: write: connection refused
```
Not sure it should pass on Mac or not.
> Update linuxkit/virtsock package. Track 10586_fixes branch.

- go/pkg/libproxy/frame.go
- go/pkg/libproxy/frame_test.go
- go/pkg/libproxy/loopbackconn.go
- go/pkg/libproxy/multiplexed.go
- go/pkg/libproxy/multiplexed_test.go
- src/forwarder/multiplexer.ml
Previously it was possible for a client to send a `Data` payload after a `Shutdown` or `Close` which would break the Go multiplexer's main loop, because it would get `EOF` from `io.CopyN`. This PR handles this error by discarding the unexpected data and processing the next message.
To make the code clearer this PR also
- removes unnecessary `error` cases from the Go code
- creates helper predicates `is_read_eof` and `is_write_eof` in the OCaml code.
> Multiplexer: handle data after EOF

- go/pkg/libproxy/multiplexed.go
- go/pkg/vpnkit/dialer.go
- src/forwarder/multiplexer.ml
- src/forwarder/multiplexer.mli
- src/hostnet/forward.ml
On the Mac a connection to `vpnkit-forwarder` is first accepted by `hyperkit` and forwarded. If `vpnkit-forwarder` hasn't started yet then the connection is immediately closed-- this permanently breaks the forwarding.
This PR makes the client reconnect if the multiplexer dispatcher has shutdown.
> Reconnect the connection multiplexer on failure

- .circleci/config.yml
- src/forwarder/multiplexer.ml
- src/hostnet_test/test_forward_protocol.ml
A badly-behaved client could send Shutdown after Close, for example if the Proxy.proxy function in `vpnkit` throws an exception for one of the directions, the function will return and the `Lwt.finalize` will call `close`. Some time later the other copy will finish and call `close_write` which will send a Shutdown message.
This PR avoids sending Shutdown messages after Close. We already covered the case of sending Data or Close messages after Close.
> mux: ocaml: avoid sending Shutdown after Close

- go/pkg/vpnkit/port.go
- pretty-print Unix forwards correctly
- allow longer paths (previously we had a limit of 100 bytes - some overhead due to base64 encoding)
> Fixes for Unix domain socket forwarding

- go/Dockerfile.userland-proxy
The `vpnkit-userland-proxy` doesn't use any of the common libraries.
This speeds up the build.
> Remove `make test` from `vpnkit-userland-proxy`

- go/.dockerignore
- go/Dockerfile.userland-proxy
- simplify the `Dockerfile` by removing `make` and following the LinuxKit standard
- excluding the Dockerfiles from the build context to avoid unnecessary rebuilds
> go: improve build of vpnkit-userspace-proxy

- go/Dockerfile.userland-proxy
COPY is less powerful than ADD so prefer COPY in this case.
> go: use COPY instead of ADD in Dockerfile

- go/Dockerfile.userland-proxy
- go/cmd/vpnkit-iptables-wrapper/README.md
- go/cmd/vpnkit-iptables-wrapper/main.go
The old package used to contain both binaries and vpnkit-iptables-wrapper expects to be able to call vpnkit-userland-proxy.
> vpnkit-userland-proxy: include the vpnkit-iptables-wrapper

- src/hostnet/hostnet_dns.ml
- src/hostnet_test/slirp_stack.ml
- src/hostnet_test/suite.ml
- src/hostnet_test/test_dns.ml
From https://www.ietf.org/rfc/rfc1035.txt
> 4.2.1. UDP usage
>
> Messages sent using UDP user server port 53 (decimal).
>
> Messages carried by UDP are restricted to 512 bytes (not counting the IP
> or UDP headers).  Longer messages are truncated and the TC bit is set in
> the header.
Reported as [docker/for-mac#2160]
> dns: set the TC bit and truncate if UDP response > 512 bytes

- go/cmd/vpnkit-userland-proxy/one.go
- go/cmd/vpnkit-userland-proxy/proxy.go
When Docker attempts to expose a port on the host with
```
docker run -p <external>:<internal>
```
We have to decide whether to also bind the same port in the VM. In the case of addresses like `0.0.0.0:80` or `127.0.0.1:80` this can make sense, and it will allow running a Docker registry in a container and pushing directly to it, see [docker/for-mac#3611]
However it also opens us up to accidental port clashes between the user's ports and any that we have allocated internally. Recently this happened when a compose on kubernetes container was run with `--net=host` and bound port 8080, see [docker/compose-on-kubernetes#70].
This patch adds support for "best-effort" binding in the VM and makes this the default. This should re-enable the registry use-case while making us robust to the compose …
> vpnkit-userland-proxy: bind ports in the VM on a best-effort basis

- go/Gopkg.lock
- go/Gopkg.toml
- go/cmd/vpnkit-forwarder/main.go
- go/pkg/vpnkit/dialer_windows.go
- go/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock.go
- go/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock_fallback.go
- go/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock_linux.go
- go/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock_windows.go
- go/vendor/github.com/linuxkit/virtsock/pkg/hvsock/zsyscall_windows.go
The upstream linuxkit/virtsock API is different from that in the `10586_fixes` branch that we're using.
This PR uses a backport of the new API onto the old branch. This is useful since we're still using the old kernel in Desktop.
> Update to new virtsock API

- go/pkg/vpnkit/control/control.go
- go/pkg/vpnkit/forward/forward.go
- go/pkg/vpnkit/forward/forward_test.go
- go/pkg/vpnkit/forward/tcp.go
- go/pkg/vpnkit/forward/unix_unix.go
- go/pkg/vpnkit/forward/unix_windows.go
A caller can now set
```
controller.Forwarder.Unix.SecurityDescriptor = "<some incomprehensible SDDL string>"
```
> go: allow the Security Descriptors of forwarded Windows named pipes to be set

- go/pkg/vpnkit/forward/tcp.go
- go/pkg/vpnkit/forward/tcp_darwin.go
- go/pkg/vpnkit/forward/tcp_linux.go
- go/pkg/vpnkit/forward/tcp_windows.go
- go/pkg/vpnkit/forward/udp_darwin.go
- go/pkg/vpnkit/forward/udp_linux.go
- go/pkg/vpnkit/forward/udp_windows.go
- go/pkg/vpnkit/forward/vmnet_darwin.go
- go/pkg/vpnkit/forward/vmnet_darwin_test.go
Previously in 32ede13e84c08bdc76ac8ea17d5e84863b89637f we added a fix for TCP where we didn't set the socket to non-blocking mode. This PR replicates the fix for UDP and adds a unit test.
Related to docker/for-mac#3775
Furthermore this PR only uses the `vmnetd` code path if the bind actually fails with permission denied. In particular on Mojave, some binds will succeed (e.g. `0.0.0.0:80`) without being root.
> go: fix binding of privileged UDP ports via vmnetd

- go/pkg/libproxy/expose_port.go
- go/pkg/libproxy/forward.go
- go/pkg/libproxy/log.go
- go/pkg/libproxy/multiplexed.go
- go/pkg/libproxy/multiplexed_test.go
- go/pkg/libproxy/network_proxy_test.go
- go/pkg/libproxy/proxy.go
- go/pkg/libproxy/stream_proxy.go
- go/pkg/libproxy/tcp_proxy.go
- go/pkg/libproxy/udp_proxy.go
- go/pkg/libproxy/unix_proxy.go
- go/pkg/vpnkit/control/control.go
- go/pkg/vpnkit/forward/forward.go
- go/pkg/vpnkit/forward/stream.go
- go/pkg/vpnkit/forward/udp.go
- go/pkg/vpnkit/http.go
- go/pkg/vpnkit/log/log.go
- go/pkg/vpnkit/port.go
- go/pkg/vpnkit/transport/vsock.go
- add `logrus`
- use `Errorf` where appropriate
- don't log "expected" errors around closing
- attempt to hide transient Unix domain socket errors by retrying for up to 120s, assuming that these are forwards to internal services (Unix domain socket forwarding is not used by Docker)
> Go: improve the logging

- go/pkg/libproxy/handshake.go
- go/pkg/libproxy/handshake_test.go
- go/pkg/libproxy/multiplexed.go
- go/pkg/libproxy/multiplexed_test.go
- go/pkg/vpnkit/control/control.go
- go/pkg/vpnkit/dialer.go
Previously if we connected to the wrong service we would output a confusing set of error messages.
Previously if the connection returned EOF (e.g. because it was forwarded by something like `docker run -p`) we would also output a confusing set of error messages.
This patch makes the constructor `NewMultiplexer` return an error, which is the result of a handshake exchange. This means that `NewMultiplexer` is now a blocking operation.
The handshake contains the magic string
```
https://github.com/moby/vpnkit multiplexer protocol\n
```
so hopefully it will be obvious to other people what this protocol is.
For future use the handshake includes a variable length payload which could contain feature flags in the future.
> mux: perform an initial handshake to check the data connection

- go/pkg/libproxy/multiplexed.go
- go/pkg/libproxy/multiplexed_test.go
- go/pkg/vpnkit/control/control.go
- go/pkg/vpnkit/dialer.go
Channel IDs are allocated independently from both ends of the
multiplexer. Previously that meant that if both ends allocate channel
concurently, there was a clash of channel IDs leading to a channel being
stuck.
This commit fixes that by allowing to indicate that one end should
allocate ids backwards.
Signed-off-by: Simon Ferquel <simon.ferquel@docker.com>
> Fix a hang when channels are opened from both ends concurrently

- go/pkg/vpnkit/control/control.go
Signed-off-by: Guillaume Rose <guillaume.rose@docker.com>
> forwards field is protected behind a mutex. Use it.

- go/pkg/libproxy/stream_proxy.go
They happen every time the client named pipe do a close and it don't hide any errors
(it's quite similar to `is not connected` filtering)
> Remove `is being closed.` logs in proxystream

- go/pkg/libproxy/stream_proxy.go
They happen every time the server named pipe is about closing, it's similar to EOF
Signed-off-by: ebriney <emmanuel.briney@docker.com>
> Remove `is being closed.` logs in proxystream when copying

- c/vpnkit-tap-vsockd/tap-vsockd.c
This makes the tap-vsockd executable wait a shorter amount of time while waiting for vpnkit backend to be ready.
> Run a tighter retry loop when connecting to the vpnkit backend

- go/pkg/vpnkit/transport/vsock_darwin.go
On Darwin a Unix socket path can only be 104 bytes long. We use long paths when talking to hyperkit
(`~/Library/Containers/com.docker.docker/...`) so we often hit this limit if the user has a long username.
A common workaround is to `chdir` into the `~/Library/Containers/com.docker.docker` folder (as would happen naturally if running in a macOS sandbox) and then use relative paths.
This patch checks the path lengths and constructs a relative path if necessary.
> transport: work around Unix socket path lengths on Darwin

- go/Gopkg.lock
- go/pkg/vpnkit/transport/unix_darwin.go
- go/pkg/vpnkit/transport/unix_linux.go
- go/pkg/vpnkit/transport/unix_unix.go
- go/pkg/vpnkit/transport/unix_unix_test.go
- go/pkg/vpnkit/transport/vsock_darwin.go
- go/vendor/github.com/stretchr/testify/require/doc.go
- go/vendor/github.com/stretchr/testify/require/forward_requirements.go
- go/vendor/github.com/stretchr/testify/require/require.go
- go/vendor/github.com/stretchr/testify/require/require_forward.go
- go/vendor/github.com/stretchr/testify/require/requirements.go
On Mac the max socket length is 104 which includes a NULL on the end. A Go path of length 104 will fail. The effective max length is 103.
This patch includes a test case which checks that, when the bind fails, the length is > maxUnixSocketPathLen.
Signed-off-by: <David Scott dave.scott@docker.com>
> transport: fix off-by-one in the max socket path

- go/pkg/vpnkit/forward/forward_test.go
- go/pkg/vpnkit/forward/stream.go
- go/pkg/vpnkit/forward/tcp.go
- go/pkg/vpnkit/forward/udp.go
- go/pkg/vpnkit/forward/unix_unix.go
- go/pkg/vpnkit/forward/unix_windows.go
This makes sure forwarded UDP and TCP services on random ports report back their randomly assigned ports.
> Handle random port correctly: report assigned port

- repo/darwin/packages/upstream/ounit.2.0.8/url
The current URL for `ounit` results in a 404 file not found error.
> Update the URL for the ounit Package

- go/Makefile
> go: remove hardcoded GOARCH to support multiarch builds

- go/pkg/vpnkit/forward/udp_darwin.go
- go/pkg/vpnkit/forward/vmnet_darwin.go
- go/pkg/vpnkit/forward/vmnet_darwin_test.go
This is smaller and easier to get than a full *net.UDPConn.
Split from #514 in case I mess up the `go.mod` transition at the same time.
Unfortunately the CI builds the Go code under Linux but the Mac CI is broken, allowing this kind of breakage to slip through.
> go: use narrower UDPListener interface

- Dockerfile
- vpnkit.opam
The failure looks like:
```
ocamlc lib/.uri.objs/byte/uri_re.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /home/opam/.opam/4.07/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.uri.objs/byte -no-alias-deps -o lib/.uri.objs/byte/uri_re.cmo -c -impl lib/.wrapped_compat/Uri_re.ml-gen)
File "lib/.wrapped_compat/Uri_re.ml-gen", line 1, characters 99-110:
Error: Unbound module Uri__Uri_re
```
I suspect it's due to a missed dependency within the code itself, probably due to the old packages and `dune`/`jbuilder` version. Building the package separately seems to hide the problem, which is enough until we can upgrade a lot of the dependencies.
> Work around build failure in uri package

- Dockerfile
- src/hostnet/hostnet_dns.ml
- vpnkit.opam
- update to OCaml 4.10
- use the upstream version 2 https://github.com/ocaml/opam-repository with some `opam pin`s, rather than an old subset of the ancient version 1 metadata in the repo
- increase concurrency (after workaround for `Uri`/`Re` problem)
> Improve dockerfile build

- src/bin/bind.ml
- src/bin/dune
- src/bin/logging.ml
- src/bin/main.ml
- src/hostnet/forward.ml
- src/hostnet/host.ml
- src/hostnet/hostnet_dns.ml
- src/hostnet/slirp.ml
- src/hostnet/vmnet.ml
- vpnkit.opam
Previously we supported 3 log "destinations":
1. `quiet`: stderr
2. `asl`: the Apple System Log
3. `eventlog`: the Windows event log
This PR removes the `asl` and `eventlog` systems to simplify the build dependencies. The `eventlog` mode was never used anywhere and I'm not sure if it's implemented correctly. The `asl` mode is being used in Docker Desktop but this isn't a good idea: the system logs are difficult to filter and full of spam. It's much easier to simply log to stderr and rely on another tool to send the logs to the correct destination (e.g. `docker logs`)
At the same time the output format has been changed to resemble other Go programs for consistency, e.g.:
```
time="2021-04-17T10:56:51Z" level=info msg="usernet: Increasing preemptive thread pool size to 1024 threads"
``` …
> Improve / simplify logging

- vpnkit.opam
> jbuilder is deprecated, so use dune (the new name for jbuilder)

- .circleci/config.yml
- Dockerfile
- Makefile.darwin
- src/hostnet/forward.ml
- src/hostnet/hostnet_http.ml
- src/hostnet_test/test_http.ml
- vpnkit.opam
This also removes the fork of `hvsock`, replacing it with a regular v2.0.0.
> Bump base64 to >= 3.0.0

- MAINTAINERS
Also the MAINTAINERS file was missing a reference to @guillaumerose so I've corrected that too.
> Propose ebriney as a new maintainer

- Dockerfile
- appveyor.yml
- go/Makefile
- go/pkg/libproxy/loopbackconn.go
- go/pkg/libproxy/multiplexed.go
- go/pkg/libproxy/multiplexed_test.go
- go/pkg/libproxy/udp_encapsulation.go
- go/pkg/vpnkit/client.go
- go/pkg/vpnkit/control/control.go
- go/pkg/vpnkit/control/control_test.go
- go/pkg/vpnkit/http/http.go
- scripts/appveyor.sh
Previously attempting to expose an existing port would return an error, which becomes an HTTP 500 internal server error.
This patch makes exposing a port idempotent, just like un-exposing a port already is.
Previously there was a port leak if the user requested any port (`0`) because we would store `0` in our map, and then look up the real port in `Unexpose` and fail to find it.
To make the API clearer, we switch to `PUT` and `DELETE` (instead of `POST`) but for backwards compatibility retain the `POST` handlers.
Minor additional updates:
- switch from `*sync.Mutex` to `sync.Mutex` where we are already using a pointer receiver, since the `nil` value is a valid mutex
- run the unit tests with the race detector enabled
- avoid logging as errors 3 expected conditions (all variations of an …
> Exposing a port should be idempotent and fix an ephemeral port leak

- go/Dockerfile.kube-forwarder
Update `Dockerfile.kube-forwarder` to use golang:1.16-alpine as parent image.
> Update base image and cleanup Dockerfile for kube-vpnkit-forwarder

- go/pkg/vpnkit/forward/tcp.go
- go/pkg/vpnkit/forward/tcp_darwin.go
- go/pkg/vpnkit/forward/tcp_linux.go
- go/pkg/vpnkit/forward/tcp_windows.go
- go/pkg/vpnkit/forward/udp_darwin.go
- go/pkg/vpnkit/forward/vmnet_darwin.go
- go/pkg/vpnkit/forward/vmnet_darwin_test.go
By default Go sets `O_CLOEXEC` on file descriptors it creates. This ensures that they aren't accidentally inherited over fork+exec. 
When binding a port on the host we first try `net.Listen`. On modern macOS this works for
- unprivileged ports (> 1024)
- privileged ports on `INADDR_ANY` (all IPs)
Unfortunately it doesn't work for privileged ports on specific IPs, such as `127.0.0.1:80`. For these cases we contact a helper process which runs as root, which binds the port and then uses `sendmsg` to transmit it to us. Unfortunately when we `recvmsg` a file descriptor, the resulting descriptor does not have `O_CLOEXEC` set, so it is captured by future subprocesses. Even if the parent process calls `close()`, the port is still in use by the subprocesses and can't be re-bound. This caused the …
> Set O_CLOEXEC on received file descriptors

- go/pkg/vpnkit/transport/transport.go
- go/pkg/vpnkit/transport/unix_unix.go
- go/pkg/vpnkit/transport/unix_unix_test.go
- go/pkg/vpnkit/transport/unix_windows.go
- go/pkg/vpnkit/transport/unix_windows_test.go
- go/pkg/vpnkit/transport/vsock_darwin.go
- go/pkg/vpnkit/transport/vsock_linux.go
- go/pkg/vpnkit/transport/vsock_windows.go
This is needed on some Windows machines to set the ACLs on the named pipes to ensure we can connect to them.
> transport: allow named pipe SecurityDescriptor to be set

- src/hostnet/slirp.ml
I occasionally observed stalls because of this
when using NuttX sim as a client.
> Ignore a dup SYN for older connections as well

- Dockerfile
- Makefile
- README.md
- appveyor.yml
- scripts/licenses.ml
We don't need to pin unreleased versions of hvsock, protocol-9p since these have been released upstream.
> Simplify build instructions

- go/pkg/vpnkit/config.go
- scripts/licenses.ml
- src/bin/logging.ml
- src/hostnet/hostnet_http.ml
- src/hostnet/hostnet_http.mli
- src/hostnet_test/suite.ml
- src/hostnet_test/test_http.ml
This allows an admin to set an allow list, such that requests for other domains / CIDRs / IPs will be blocked.
It re-uses the existing HTTP exclude matching functions.
There is still some work needed to distinguish the case `None` and `Some []` in the .json configuration.
> HTTP: add an optional allow list to the proxy

- go/pkg/vpnkit/config.go
> go: fix typo in struct field name

- go/Dockerfile
- go/Makefile
- go/pkg/vpnkit/control/control.go
- scripts/licenses.ml
Previously if -data-connect was connecting to a port forward and the remote isn't running, it would connect but then get an immediate EOF. Unfortunately it would try again and spin in a tight loop. This is likely to happen when shutting down, as the remote can stop before the port forward closes.
This patch adds a one second delay to break the spinning and a log every 30s to highlight any persistent problem.
> vpnkit-forwarder: avoid -data-connect spinning

- scripts/licenses.ml
https://github.com/mirage/mirage-channel/releases/tag/v4.1.0 was released a few hours ago.
I’m still a bit puzzled as to why the dependencies aren’t pinned. What did I miss? 🤔
> Update licenses versions

- scripts/licenses.ml
This silently adds `fd-send-recv.2.0.1` with an empty type.
> Fix typo in licenses

- src/hostnet/vmnet.ml
- src/hostnet_test/slirp_stack.ml
- src/hostnet_test/test_nat.ml
```
File "src/hostnet/vmnet.ml", line 327, characters 30-42:
327 |   let client_negotiate ~uuid ?preferred_ip ~fd =
^^^^^^^^^^^^
Error (warning 16 [unerasable-optional-argument]): this optional argument cannot be erased.
```
> Fix warning 16 (optional argument cannot be erased)

- src/hostnet/slirp.ml
Previously we used "sizeof_ethernet" which is the "size of the Ethernet header" (!) Most of the time the buffer is big enough anyway, but this explains the occasional Cstrict.blit errors in the log when a 14 byte buffer is used.
> switch: request a large enough buffer for the MTU

- src/hostnet/hostnet_http.ml
- src/hostnet/slirp.ml
- use "HTTP proxy" rather than "transparent HTTP ..." because the proxy has both transparent and explicit/non-transparent modes
- demote some error logs to warnings, where it's the client misbehaving rather than us
> Improve logs, demote some errors to warnings

- src/hostnet/slirp.ml
- src/hostnet_test/test_half_close.ml
After a successful connection forwarding to a server, if the server
disappears, a tentative to connect the server again will be accepted by
vpnkit even if vpnkit failed to reach the server.
Ensure this does not occur by calling unlisten.
Add test for valid and invalid connection cases
Signed-off-by: Frédéric Dalleau <frederic.dalleau@docker.com>
> Unlisten sockets after they disconnect

- .gitignore
- scripts/licenses.ml
- vpnkit.opam
This adds pin-depends to the opam file to make it easier to build with simpler opam invocations.
> metadata fixes for opam/ocaml versions

- go/pkg/libproxy/multiplexed.go
- go/pkg/libproxy/multiplexed_test.go
- go/pkg/libproxy/udp_encapsulation.go
- go/pkg/vpnkit/forward/forward_test.go
If the link has high latency then it's useful to use larger buffers
> libproxy: allow read/write buffers to be set

- go/pkg/libproxy/loopbackconn.go
- go/pkg/libproxy/loopbackconn_test.go
- go/pkg/libproxy/multiplexed.go
- go/pkg/libproxy/multiplexed_test.go
- `Close()` allows us to cleanly shutdown the multiplexer (similar to `Close()` on a `net.Listener`)
- `NewLoopback()` satisfies the interface of the multiplexer, which makes it easier to write test cases in downstream projects
> libproxy: ability to Close(), expose NewLoopback()

- vpnkit.opam
- opam: upper-bound on cmdliner (use of deprecated API)
> attempt to fix ocaml-ci

- src/bin/config/discover.ml
Adds a fix to the `uname` command / subprocess spawned which was not cleaned up / reaped appropriately on Darwin.
The result was a zombie process / resource leak that lingered in the process table.
Fixes #592
> Ensure uname subprocess is cleaned up

- go/pkg/tunnel/forwards.go
- go/pkg/tunnel/tunnel.go
- src/bin/main.ml
- src/hostnet/configuration.ml
- src/hostnet/forwards.ml
- src/hostnet/forwards.mli
- src/hostnet/hostnet_http.ml
- src/hostnet/hostnet_http.mli
- src/hostnet/slirp.ml
- src/hostnet_test/suite.ml
This is based on the existing "gateway forwards" mechanism which allowed traffic sent to the gateway to be forwarded.
A `forwards.json` can be dynamically updated with IP network matches and Unix domain socket / Windows named pipe paths. When a SYN arrives, a request is sent on the Unix domain socket, allowing the server to reject or accept the request. Assuming the connection is accepted, the handshake is completed and traffic flows.
> Add a mechanism to forward outgoing TCP via a Unix domain socket

- src/bin/main.ml
- src/hostnet/slirp.ml
- src/hostnet/slirp.mli
This adds a third HTTP proxy configuration option. We already have:
1. command-line
2. configuration file
This adds an HTTP server. The caller can run:
```
vpnkit --http-api-path /tmp/foo.sock --ethernet /tmp/ethernet.sock
```
and then
```
curl --unix-socket /tmp/foo.sock http://localhost/http_proxy.json
```
and
```
curl -X POST -d json --unix-socket /tmp/foo.sock http://localhost/http_proxy.json
```
> HTTP: add --http-proxy-api <path>

- src/hostnet/host.ml
The segfault looks like this:
```
Thread 3 Crashed:
0   com.docker.vpnkit             	       0x10231b8b8 camlLuv__Helpers__set_reference_inner_1334 + 40
1   com.docker.vpnkit             	       0x10231b8b8 camlLuv__Helpers__set_reference_inner_1334 + 40
2   com.docker.vpnkit             	       0x1029c1108 caml_callback_exn + 24 (callback.c:111) [inlined]
3   com.docker.vpnkit             	       0x1029c1108 caml_callback + 44 (callback.c:165)
4   com.docker.vpnkit             	       0x102980aa0 luv_async_trampoline + 44 (helpers.c:64)
5   com.docker.vpnkit             	       0x102986a98 uv__async_io + 308 (async.c:163)
6   com.docker.vpnkit             	       0x102996be8 uv__io_poll + 992
7   com.docker.vpnkit             	       0x102986ec4 uv_run + 372 (core.c:389)
8 …
```
> luv: calling read_start after close can segfault

- src/hostnet/hostnet_dhcp.ml
Previously users would see network glitches every 2hrs as the lease was renewed.
Since vpnkit is used in "static" environments, we can offer very long leases. This value is in seconds and > 68 years.
> dhcp: offer very long leases

- go/pkg/tunnel/tunnel.go
- go/pkg/tunnel/tunnel_test.go
We couldn't test the existing functions because basic Read/Write operations were missing.
Add the missing functions and add some tests.
> go: add missing functions and unit tests for tunnel pkg

- go/pkg/libproxy/multiplexed.go
The Write window is used to keep track of how much buffer space is free in the remote to avoid one connection blocking the rest. Previously we checked the window and decided how much to write, then dropped the metadata mutex before performing the write. In theory another Write call on the same connection could see that buffer size is free, send too much and block the connection.
Therefore Write should take ownership of the space by bumping the `current` window before dropping the lock.
> go: avoid possible overflow of the Write window

- go/pkg/libproxy/multiplexed.go
The [net.Conn interface](https://docker.atlassian.net/browse/POS-1477) says:
> // Multiple goroutines may invoke methods on a Conn simultaneously.
Previously concurrent calls to `Write()` would block for window space but only one would be woken up by a `Signal()` when a window update is received, allowing the other call to block forever.
The handling of write timeouts was also confusing because
- `time.Sleep` couldn't be interrupted
- the condition variable `Wait()` was on a temporary goroutine
> go: allow concurrent Write calls

- go/pkg/libproxy/multiplexed.go
Close() holds the channel mutex then calls decrChannelRef which acquires the metadata mutex.
In DumpState() we should not hold the metadata mutex and then acquire the channel mutex.
> go: don't hold the metadata mutex and then acquire the channel mutex

- go/pkg/libproxy/multiplexed.go
- go/pkg/libproxy/multiplexed_test.go
It's legal for a single `net.Conn` to be shared between goroutines, for example calling `Close()` on `<- ctx.Done()` while calls are blocked in `Read` and `Write`.
The multiplexer does not impose an ordering in `send`: each concurrent call simply competes for the `writeMutex`.
Therefore sequences we considered invalid are actually possible:
- `Close(id)` then `Window(id)`
- `Close(id)` then `Write(id)`
- `Close(id)` then `Shutdown(id)`
Previously we detected these invalid sequences and shutdown the whole multiplexer. The effect would be to completely disable port forwarding.
Instead we drop these out-of-order packets and log (just in case it's interesting). There is a very small risk that an old out-of-order packet could be mixed up with a new packet if the channel ID is reused, but we …
> multiplexer: don't fail if Close() is called concurrently to Read(), Write()

- scripts/licenses.ml
- vpnkit.opam
This allows dune.3.16.0 to be installed, which in turn will allow testing the forthcoming dune package management feature in https://discuss.ocaml.org/t/ann-dune-developer-preview-updates/15160
> Fix build with latest dune

- src/hostnet/host.ml
- src/hostnet/hostnet_dns.ml
- src/hostnet/hostnet_http.ml
- src/hostnet/sig.ml
- src/hostnet_test/test_dns.ml
Fixes #509 and https://github.com/moby/moby/issues/47628.
1. `Dns.resolve` now returns  `(rr list, unit) result` to distinguish between `[]` resulting from NOERROR or NXDOMAIN.
- Currently only returns NXDOMAIN on any kind of error.
- `Dns.getaddrinfo` returns `(rr list, Msg) result` with no error handling just like current behavior
2. `Make.answer` returns answers (including `[]`) if there is no error, otherwise NXDOMAIN is returned.
3. Added NOERROR and NXDOMAIN test cases.
> Correctly return NOERROR even if host resolver returned empty list

- src/hostnet/host.ml
This pull request addresses a long-standing issue where DNS lookups within containers, especially those running in rootless Docker-in-Docker (DIND) environments using VPNKit, would fail with an `NXDOMAIN` error. 
This often occurred even when valid IP addresses were present in the DNS response, or for specific record types like SRV records.
*   **DNS Lookup Errors in Rootless DIND**
*   Related Issue: moby/moby#47628
*   When running containers in `dind-rootless` mode, DNS lookups would fail with `NXDOMAIN`.
*   This was particularly evident when the upstream DNS server stripped out IPv6 addresses. For example, commands like `apk add` in `alpine` containers would fail due to these DNS errors.
*   This behavior was reproduced across multiple dind images.
*   **NXDOMAIN for SRV Records**
* …
> Fix(DNS): Handle EAI_NODATA as success (empty address list) in getaddrinfo

- .dockerignore
- .github/workflows/tests-in-docker.yml
- Dockerfile.test
- src/hostnet_test/suite.ml
Note the ICMP tests are currently broken on Linux, so comment out for now.
Run by:
```
docker build -t test -f Dockerfile.test .
```
> e2e: add Dockerfile.text to run tests
